### ISSUE TITLE
Error adding miri-preview extension

### ISSUE THREAD

**Issue by wykurz** [oxalica/rust-overlay#102]
I'm seeing the following error when trying to add miri-preview extension to my overlay:

```
error: Component resolution failed for rust-default-1.65.0-nightly-2022-09-16
       Host component `miri-preview` doesn't support `x86_64-unknown-linux-gnu`
       note: profile components: rustc cargo rust-std rust-mingw rust-docs rustfmt-preview clippy-preview
       note: selected targets: x86_64-unknown-linux-gnu
       note: selected extensions: rust-analysis rust-src miri-preview
       note: components available for x86_64-unknown-linux-gnu: cargo clippy clippy-preview llvm-tools-preview reproducible-artifacts rls rls-preview rust rust
```

I _think_ that `miri-preview` ought to work with `x86_64-unknown-linux-gnu`... Is there some other target I should be choosing? If so, I didn't see it documented anywhere.

Here's my slightly simplified nix shell for reference:
```
let
  rust_overlay = import (builtins.fetchTarball https://github.com/oxalica/rust-overlay/archive/master.tar.gz);
  unstable = import <nixos-unstable-small> { };
  nixpkgs = import <nixpkgs> { overlays = [ rust_overlay ]; };
  myrust = nixpkgs.rust-bin.nightly.latest.default.override {
    extensions = [ "rust-analysis" "rust-src" "miri-preview" ];
  };

in
  with nixpkgs;
  stdenv.mkDerivation {
    name = "rust-shell";
    buildInputs = [
      unstable.rust-analyzer  # must be before rust so the PATH picks this one first
      myrust
      cargo-audit
      cargo-bloat
      cargo-deny
      cargo-edit
      cargo-flamegraph
      cargo-generate
      cargo-outdated
      pkgconfig
      openssl
    ];
    RUST_SRC_PATH = "${myrust}/lib/rustlib/src/rust/src";
  }
```

**Comment by oxalica** [comment]
> I think that miri-preview ought to work with x86_64-unknown-linux-gnu... 

No for nightly-2022-09-16.
https://rust-lang.github.io/rustup-components-history/

**Comment by oxalica** [comment]
By building your nix expression, here's what I got. I already provide that URL in the error message. But seems you are leaving that out. Maybe your cache of rust-overlay is outdated? Also that 2022-09-{16,17} both have `miri` component missing.

```
error: Component resolution failed for rust-default-1.65.0-nightly-2022-09-17
       Host component `miri-preview` doesn't support `x86_64-unknown-linux-gnu`
       note: profile components: rustc cargo rust-std rust-mingw rust-docs rustfmt-preview clippy-preview
       note: selected targets: x86_64-unknown-linux-gnu
       note: selected extensions: rust-analysis rust-src miri-preview
       note: components available for x86_64-unknown-linux-gnu: cargo clippy clippy-preview llvm-tools-preview reproducible-artifacts rls rls-preview rust rust-analysis rust-analyzer rust-analyzer-preview rust-docs rust-src rust-std rustc rustc-dev rustc-docs rustfmt rustfmt-preview
       note: check here to see all targets and which components are available on each targets:
             https://rust-lang.github.io/rustup-components-history
(use '--show-trace' to show detailed location information)
```

**Comment by wykurz** [comment]
OK, that's fair. I saw the error message but didn't check the URL, the "miri-preview doesn't support x86..." confused me. Thanks for the pointers though!

Unfortunately looks like the nightly builds that had miri component (2022-09-13,14,15) are no longer available on nixos cache (or maybe it's just having a bad day?). 

Do you have any suggestions of what is a good way to get miri with rust + nix? Just try another day?

**Comment by oxalica** [comment]
> Unfortunately looks like the nightly builds that had miri component (2022-09-13,14,15) are no longer available on nixos cache

We are porting binary distributions from rustup server. It's fine that the derivation is not in the cache, because itself is just `curl`ing from rustup server.

> Do you have any suggestions of what is a good way to get miri with rust + nix? Just try another day?

Please read [README](https://github.com/oxalica/rust-overlay#cheat-sheet-common-usage-of-rust-bin) carefully.

> - Latest nightly rust profile.
> ```
> rust-bin.selectLatestNightlyWith (toolchain: toolchain.default) # or `toolchain.minimal`
> ```
> *Note: Don't use rust-bin.nightly.latest. Your build would fail when some components missing on some days. Always use selectLatestNightlyWith instead.*

**Comment by wykurz** [comment]
I was actually trying with a pinned nightly and it was failing, but I think it's happy now! Anyway, here's the `myrust` bit that is finally working for me:
```
  myrust = nixpkgs.rust-bin.nightly."2022-09-15".default.override {
    extensions = [ "rust-analysis" "rust-src" "miri-preview" ];
  };
```

Thanks for your help @oxalica , much appreciated!
