### ISSUE TITLE
Latest rust stable version (2022-08-08) is outdated as the current latest is 2022-08-11

### ISSUE THREAD

**Issue by wykurz** [oxalica/rust-overlay#103]
Building rust-overlay with `rust-bin.stable.latest` provides:
```
rustc --version
rustc 1.63.0 (4b91a6ea7 2022-08-08)
```

But the current latest release is 1.63.1 (2022-08-11).

**Comment by oxalica** [comment]
Here's what I tested on Arch Linux.
```
$ rustup install stable
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2022-08-11, rust version 1.63.0 (4b91a6ea7 2022-08-08)
info: downloading component 'cargo'
```

Where do you find 1.63.1?

**Comment by wykurz** [comment]
You're right... Sorry for that! I think the dates got me confused, rustc is showing 2022-08-08 while rust RELEASES (and rustup apparently) show 2022-08-11.
