### ISSUE TITLE
Update flake instructions for NixOS in Readme

### ISSUE THREAD

**Issue by benwis** [oxalica/rust-overlay#104]
Hi!
I'm  new to Nix, and trying to use this as part of a flake config to configure a default rust and per project rust toolchain.

It appears that the instructions are incorrect for flakes in NixOS, as it now gives this warning: 
```
trace: warning: rust-overlay's flake output `overlay` is deprecated in favor of `overlays.default` for Nix >= 2.7
```
I'd submit a PR but I'm struggling to add it to overlay.defaults. Could that be updated?

**Comment by oxalica** [comment]
Seems there is a line in README being outdated.
`nixpkgs.overlays = [ rust-overlay.overlay ];`
should be now
`nixpkgs.overlays = [ rust-overlay.overlays.default ];`

https://github.com/oxalica/rust-overlay/tree/f48045bb46f6eef8314b9fe01b7db9dcdbca1e10#use-in-nixos-configuration

PRs are welcome.
