### ISSUE TITLE
FR: Respect `features` in Cargo.toml

### ISSUE THREAD

**Issue by bakhtiyarneyman** [oxalica/rust-overlay#106]
Currently, all features seem to be enabled, which means that the result of compilation is not identical to what the Cargo.toml prescribes. Sometimes compilation fails because of this, and this requires the user to give the generated `Cargo.nix` a manual surgery editing a whole bunch of records in the transitive closure of the offending package. This is a non-ideal user experiance.

**Comment by oxalica** [comment]
Are you targeting the wrong repo? `rust-overlay` doesn't have anything to do with `Cargo.nix`.

**Comment by bakhtiyarneyman** [comment]
You are absolutely right!
