### ISSUE TITLE
Can't compile for Tier 3 target

### ISSUE THREAD

**Issue by mixedCase** [oxalica/rust-overlay#109]
```
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
    rust-overlay.url = "github:oxalica/rust-overlay";
  };

  outputs = { self, nixpkgs, flake-utils, rust-overlay, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        overlays = [ (import rust-overlay) ];
        pkgs = import nixpkgs {
          inherit system overlays;
        };
        rust-distro = pkgs.rust-bin.nightly."2022-10-14".default.override {
          extensions = [ "rust-src" "cargo" "rustc" ];
          targets = [ "riscv32imc-esp-espidf" ];
        };
      in {
        devShell = pkgs.mkShell {
          RUST_SRC_PATH = "${rust-distro}/lib/rustlib/src/rust/library";
          buildInputs = with pkgs; [
            rust-distro
            clang
          ];
        };
      });
}
```

Fails with:
```
error: Component resolution failed for rust-default-1.66.0-nightly-2022-10-14
       Unknown target `riscv32imc-esp-espidf`, typo or not supported by this version?
       note: profile components: rustc cargo rust-std rust-mingw rust-docs rustfmt-preview clippy-preview
       note: selected targets: x86_64-unknown-linux-gnu riscv32imc-esp-espidf
       note: selected extensions: rust-src cargo rustc
       note: components available for x86_64-unknown-linux-gnu: cargo clippy clippy-preview llvm-tools-preview miri miri-preview reproducible-artifacts rls rls-preview rust rust-analysis rust-analyzer rust-analyzer-preview rust-docs rust-docs-json rust-docs-json-preview rust-src rust-std rustc rustc-dev rustc-docs rustfmt rustfmt-preview
       note: check here to see all targets and which components are available on each targets:
             https://rust-lang.github.io/rustup-components-history
(use '--show-trace' to show detailed location information)
```

My `.cargo/config.toml` defines `unstable.build-std = ["std", "panic_abort"]` so according to https://esp-rs.github.io/book/dependencies/installing-rust.html#risc-v-esp32-c3 it should build despite being a Tier 3.

Also tried using a rust-toolchain file to identical results.

**Comment by oxalica** [comment]
According to the docs you quoted,
> The standard library target (riscv32imc-esp-espidf) is currently Tier 3, and does not have prebuilt objects distributed through rustup, therefore the -Z build-std unstable cargo feature is required within your project.

`rust-overlay` just fetches and patches prebuilt std and rustc for you. And there is surely no prebuilt binaries for `riscv32imc-esp-espidf`. Nothing went wrong here.

The compiler `rustc` itself is currently multi-targeting. If you want to build std yourself, you only need `rust-src` and compile it according to the docs (you may also need a linker for your target). No need to specify that target in `rust-overlay` though.

**Comment by mixedCase** [comment]
Thanks for the prompt answer. Would you happen to know if I there's any Nix facility that would allow me to build the std for that target if rust-overlay cannot do it?

**Comment by oxalica** [comment]
> Would you happen to know if I there's any Nix facility that would allow me to build the std for that target if rust-overlay cannot do it?

If you don't care about building std manually, you could just leave out `targets` and follow the rustup docs to build std. I'm not sure if that's possible to do it with Nix derivation without introducing IFDs or impure-ness.
