### ISSUE TITLE
Instructions on obtaining the linker for cross-compilation to Windows?

### ISSUE THREAD

**Issue by werner291** [oxalica/rust-overlay#11]
Oooh, a near-empty issue tracker, time for me to dump my problems in it!

On a more serious note... Thank you for taking the time to bring some improvements to the Nix/Rust ecosystem. 

I'm having significant difficulty getting cross-compilation to Windows to work. Here's my `shell.nix` file:

```
let 

  pkgs = import <nixpkgs> {
    overlays = [
      (import (builtins.fetchTarball "https://github.com/oxalica/rust-overlay/archive/master.tar.gz"))
    ];
  };

  chan = (pkgs.rustChannelOf {
    date = "2021-01-15";
    channel = "nightly";
  }).rust.override {
    targets = [ "x86_64-pc-windows-gnu" ];
    extensions = [
      "rust-src"
      "rustc-dev"
    ];
  };

in 
    pkgs.mkShell {
        buildInputs = with pkgs; [
            chan
        ];
    }
```

My code seems to compile fine, but cargo can't find the linker:
```
error: linker `x86_64-w64-mingw32-gcc` not found
  |
  = note: No such file or directory (os error 2)
```

I understand I need to bring the mingw linker into the build environment somehow, but so far am running into nothing but arcane errors and compilation failures, even when trying the various apparent solutions floating around on the Internet.

Since you seem to be more familiar with the combination of Rust and Nix than me (I'm a bit of a Nix noob still...), can you offer any advice? I also think that adding some instructions along those lines to the readme would be invaluable to people who are in my situation.

**Comment by werner291** [comment]
Solved it!

My shell file ended up looking like this:

```
let 

  pkgs = import <nixpkgs> {
    overlays = [
      (import (builtins.fetchTarball "https://github.com/oxalica/rust-overlay/archive/master.tar.gz"))
    ];
  };

  rchan = (pkgs.rustChannelOf {
    date = "2021-01-15";
    channel = "nightly";
  }).rust.override {
    targets = [ "x86_64-pc-windows-gnu" ];
    extensions = [
      "rust-src"
      "rustc-dev"
    ];
  };
  
  pkgs-mingw = import <nixpkgs> { crossSystem = {config = "x86_64-w64-mingw32"; }; };

in 
    pkgs-mingw.mkShell { 
        nativeBuildInputs = [ rust ];
        buildInputs = [ rust pkgs-mingw.windows.pthreads pkgs-mingw.windows.mingw_w64_pthreads ]; 
        
    }

```

Notice: I'm essentially importing <nixpkgs> twice! The version that is used with the rust overlay is different from the one that has the `crossSystem` option set. I believe this is because the overlay tries to install the target for the "current" system, while Rust doesn't have a target for "x86_64-w64-mingw32".

Also, about clueless people like me: the difference between `nativeBuildInputs` and `buildInputs` matterswhen cross-compiling.

==========

To the maintainer: maybe you could mould this into a more proper approach? The separate versions of nixpkgs feels kinda hacky.

**Comment by oxalica** [comment]
>  I'm essentially importing twice! 

You can import `nixpkgs` once with both `overlay` and `crossSystem`. But you need to explicitly bring `rust` from `buildPackages`, eg. `nativeBuildInputs = [ (buildPackages.rustChannel { .. }) ];`. It's an upstream issue (https://github.com/NixOS/nixpkgs/issues/49526) when the expression is not called by `callPackage`.

> Maybe you could mould this into a more straightforward process, or document this somewhere?

I added an example for cross compiling environment for `aarch64-linux` in master. Hope it helps.
https://github.com/oxalica/rust-overlay/blob/0bb9ef6d8b34e5579d7384201f3106a49ce3deca/examples/cross-aarch64

Another thing worth mentioning is that `cargo` doesn't add cross system prefix for linker by default through they are in scope. You need to specify it in `.cargo/config` or through environment `CARGO_TARGET_<triple>_LINKER`.
