### ISSUE TITLE
Support semver major and minor as well

### ISSUE THREAD

**Issue by Milo123459** [oxalica/rust-overlay#112]
It would be useful if a version like `1.62` is provided, it automatically finds the latest release of `1.62` (in this case, `1.62.1`) and uses that as the version. If there isn't a patch version, it should just fill out to `.0` (for example, if `1.65` is provided, which doesn't have a patch version, it would be expanded to `1.65.0`)

**Comment by oxalica** [comment]
If you want a `rust-bin.stable."1.65"` alias, I think it's not so worthy. Fields here should be better canonical. `latest` is already an exception which I'm not happy with.

For now, you could use `rust-toolchain` file with `fromRustupToolchainFile` or just `fromRustupToolchain` to achieve this. It supports `channel = "1.65"`. See also https://github.com/oxalica/rust-overlay/issues/99#issuecomment-1200134608
