### ISSUE TITLE
How to use an older glibc version in cross-compiling ?

### ISSUE THREAD

**Issue by Athorus** [oxalica/rust-overlay#114]
Hello,

I succeeded to cross compile to my RaspberryPi Zero 2 W, did a ```patchelf --set-interpreter /lib/ld-linux-aarch64.so.1```, but  when I try to execute the binary, it complains it not finds a proper version of glibc.

```
pi@etage:~/chauffage $ target/release/c64
target/release/c64: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by target/release/c64)
target/release/c64: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by target/release/c64)
target/release/c64: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by target/release/c64)
```
On my Raspbian, only glibc 2.31 is available.

I’m sorry to be a newbee in NixOs, but could you tell me how to modify my shell.nix in order to use an older glibc ?

Here my shell.nix

```nix
# See docs/cross_compilation.md for details.
(import <nixpkgs> {
  crossSystem = "aarch64-linux";
  overlays = [ (import <rust-overlay>) ];
}).callPackage (
{ mkShell, stdenv, rust-bin, pkg-config, dbus }:
mkShell {
  nativeBuildInputs = [
    rust-bin.stable.latest.minimal
    pkg-config
  ];

  buildInputs = [ dbus ];

  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER = "${stdenv.cc.targetPrefix}cc";
}) {}
```

**Comment by oxalica** [comment]
> I succeeded to cross compile to my RaspberryPi Zero 2 W, did a patchelf --set-interpreter /lib/ld-linux-aarch64.so.1, but when I try to execute the binary, it complains it not finds a proper version of glibc.

Generally patching dependencies of binaries meant for NixOS and copying them elsewhere are not supposed to work. There will be more compatibility issues other than version mismatch. Please build it statically via `+crt-static` or *-musl targets.

**Comment by Athorus** [comment]
Thanks for your answer, you’re right: So I tried +crt by launching
```
export RUSTFLAGS="-C target-feature=+crt-static"; cargo clean; cargo build --target aarch64-unknown-linux-gnu --release
```
but I got the following errors
```
  = note: /nix/store/5rgdmd23i123vdxvcx0hnk87fdcriagf-aarch64-unknown-linux-gnu-binutils-2.39/bin/aarch64-unknown-linux-gnu-ld: cannot find -lutil: No such file or directory
          /nix/store/5rgdmd23i123vdxvcx0hnk87fdcriagf-aarch64-unknown-linux-gnu-binutils-2.39/bin/aarch64-unknown-linux-gnu-ld: cannot find -lrt: No such file or directory
          /nix/store/5rgdmd23i123vdxvcx0hnk87fdcriagf-aarch64-unknown-linux-gnu-binutils-2.39/bin/aarch64-unknown-linux-gnu-ld: cannot find -lpthread: No such file or directory
          /nix/store/5rgdmd23i123vdxvcx0hnk87fdcriagf-aarch64-unknown-linux-gnu-binutils-2.39/bin/aarch64-unknown-linux-gnu-ld: cannot find -lm: No such file or directory
          /nix/store/5rgdmd23i123vdxvcx0hnk87fdcriagf-aarch64-unknown-linux-gnu-binutils-2.39/bin/aarch64-unknown-linux-gnu-ld: cannot find -ldl: No such file or directory
          /nix/store/5rgdmd23i123vdxvcx0hnk87fdcriagf-aarch64-unknown-linux-gnu-binutils-2.39/bin/aarch64-unknown-linux-gnu-ld: cannot find -lc: No such file or directory
          collect2: error: ld returned 1 exit status
```

**Comment by Athorus** [comment]
Ok I’ve found, so I added ```glibc.static``` in ```buildInputs``` but I got an ```Segmentation fault``` :(

**Comment by Huanzo** [comment]
> Please build it statically via +crt-static or *-musl targets.

Im running into a similar problem and chose the musl route.
@oxalica You mention using the `*-musl` targets. This works for some crates but not all.
In my case I want to build a static musl binary with the `rusqlite` crate with feature `bundle`. It fetches a local bundle of sqlite3 and compiles/links it.
Now just setting the rustc target will not work here, as stdenv sets up `$CC` as `gcc` and not `musl-gcc` this will throw linking errors. Manually prepending setting the compiler (`CC=musl-gcc` cargo build ...) works.

Does this overlay provide a way to set the correct compiler for `*-musl` targets?

**Comment by Huanzo** [comment]
hmm interesting. Adding `musl` and `pkgsStatic.stdenv.cc` to buildInputs allows me to successfully build statically linked binaries.
Is this the way to go, or is there another/better way to do that?

**Comment by Athorus** [comment]
In order to compile in musl, here a shell.nix

``` nix
# See docs/cross_compilation.md for details.
(import <nixpkgs> {
  crossSystem = {
    config = "aarch64-unknown-linux-musl";
  };
  overlays = [ (import <rust-overlay>) ];
}).callPackage (
{ mkShell, stdenv, rust-bin, pkg-config, dbus }:
mkShell {
  nativeBuildInputs = [
    rust-bin.stable.latest.minimal
    pkg-config
  ];

  buildInputs = [ dbus ];

  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER = "${stdenv.cc.targetPrefix}cc";
}) {}
```

then do ```cargo build --target aarch64-unknown-linux-musl ```

For my case it almost works, but the dbus crate panic! No problem when I compile from a debian linux.

**Comment by Huanzo** [comment]
thx but I didnt really like importing nixpkgs with crossSystem because my I need to build my binary for multiple targets.

After some tinkering around I got both x86_64 and aarch64 compilation with musl working by just putting their respective compiler in the nativeBuildInputs:
```nix
        packages.amd64 =
          naerskBuildPackage "x86_64-unknown-linux-musl" {
            src = ./.;
            nativeBuildInputs = [ pkgsStatic.stdenv.cc ];
          };

        packages.arm64 =
          naerskBuildPackage "aarch64-unknown-linux-musl" {
            src = ./.;
            nativeBuildInputs =
              [ pkgsCross.aarch64-multiplatform-musl.stdenv.cc ];
            CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER =
              "${pkgsCross.aarch64-multiplatform-musl.stdenv.cc.targetPrefix}cc";
          };

        devShells.default = mkShell {
          nativeBuildInputs = [ toolchain pkgsStatic.stdenv.cc ];
          CARGO_BUILD_TARGET = "x86_64-unknown-linux-musl";
          CARGO_BUILD_RUSTFLAGS = "-C target-feature=+crt-static";
        };
```
So basically what you suggested but instead of using crossSystem I am manually specifying which compiler to pull in.

While tinkering I also encountered basically the same error you mentioned above and iirc I solved that by explicilty specifying the stdenv.cc I wanted in my nativeBuildInputs. Maybe this will also work for you?

**Comment by oxalica** [comment]
@Huanzo 
> Now just setting the rustc target will not work here, as stdenv sets up `$CC` as `gcc` and not `musl-gcc` this will throw linking errors. Manually prepending setting the compiler (`CC=musl-gcc` cargo build ...) works.
> 
> Does this overlay provide a way to set the correct compiler for `*-musl` targets?

Nixpkgs already provides static stdenv in a cross-compilation favor. If you don't like re-importing nixpkgs as in https://github.com/oxalica/rust-overlay/issues/114#issuecomment-1414553173, you can use `pkgsStatic` or `pkgsMusl`. With the following shell, and enabling `bundled` feature for `libsqlite3-sys`, I can get `rusqlite` working in a statically linked binary.
```nix
      let
        pkgs = import nixpkgs {
          system = "x86_64-linux";
          overlays = [ rust-overlay.overlays.default ];
        };
      in
        with pkgs.pkgsStatic; # Can also use `callPackage` magic, so the `buildPackages` below can be omitted.
        mkShell { # NB. mkShell from pkgsStatic, not pkgs.
          nativeBuildInputs = [
            (buildPackages.rust-bin.stable.latest.minimal.override {
              targets = [ "x86_64-unknown-linux-musl" ];
            })
          ];
          CARGO_BUILD_TARGET = "x86_64-unknown-linux-musl";
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER = "${stdenv.cc.targetPrefix}cc";
          # CARGO_BUILD_RUSTFLAGS = "-C target-feature=+crt-static"; # This is the default for rustc's musl target.
        }
```
The example here is almost exactly the same as cross-compilation setup as in [`examples/cross-aarch64`](https://github.com/oxalica/rust-overlay/blob/master/examples/cross-aarch64/shell.nix).


@Athorus 
> For my case it almost works, but the dbus crate panic! No problem when I compile from a debian linux.

I'm not familiar with `dbus` crate. But I found that the Rust toolchain has a musl libc shipped together with `std` and it is preferred. Maybe there's some bad interaction between two different musl libc. You could try to enable `vendored` feature of `libdbus-sys` and see if it helps. But, well, I think the Nix static linking issue is out of scope from `rust-overlay` or the title of this issue.
