### ISSUE TITLE
Git Dependeny failure to load

### ISSUE THREAD

**Issue by bhoudebert** [oxalica/rust-overlay#115]
Hello there,

We decided to get `rust-overlay` a try, great so far until we reach some of our repo with git dependencies in our `Cargo.toml`

So we have something like this

```Cargo.toml
our_dependency = { git = "https://github.com/xxxx/our_dependency", branch = "main"}
```

Unfortunately, doing a `nix build` now is triggering some unexpected behavior

```Shell
Caused by:
  failed to load source for dependency `our_dependency `

Caused by:
  Unable to update registry `crates-io`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)
```

The thing is it not explicitly saying it tries to load the repo correctly instead it goes through other channel (crates-io etc), maybe as fallback. Last but not least the repositoy in question is a public repo so ... there is really no reason at all to fall in any missing rights.

Tried to play with cargo option without any luck, any help appreciated.

Thanks.

**Comment by oxalica** [comment]
> Unfortunately, doing a `nix build` now is triggering some unexpected behavior

`nix build` what? `rust-overlay` only provides Rust toolchains like `rustc` and `cargo`, not tools for writing Nix derivations.
If you are running `cargo build` inside Nix derivation, it would fail because network is blocked by the builder sandbox. Please read [nixpkgs manual - buildRustPackage](https://nixos.org/manual/nixpkgs/unstable/#compiling-rust-applications-with-cargo) for more information about how to packaging Rust projects.

**Comment by bhoudebert** [comment]
Oh I really thought we could download sub dependencies like this (like naersk for example) as the crates are surely coming from internet.

Thanks for the answer.

**Comment by oxalica** [comment]
> Oh I really thought we could download sub dependencies like this (like naersk for example) as the crates are surely coming from internet.

rust-overlay is to replace `rustup` to provides you arbitrary nightly or stable version of rust compiler toolchain. We don't contain anything to packaging your own project. You may report in the wrong repo.
