### ISSUE TITLE
Setting custom rustc target

### ISSUE THREAD

**Issue by jordanisaacs** [oxalica/rust-overlay#116]
I am trying to set the rustc target to `x86_64-mustang-linux-gnu`. My attempt is to do it through the nix cross compilation setup. However, I get the following error that the default toolchain is missing. Essentially I am trying to use the default x86_64 toolchain but pass in the `--target XXX` to each rustc invocation:

```bash
error: attribute 'default' missing

       at /nix/store/l2xq80vipgjr359wha37w1ban2g4dhvp-source/flake.nix:32:67:

           31|       (self: super: let
           32|         rust = super.rust-bin.selectLatestNightlyWith (toolchain: toolchain.default.override {extensions = ["rust-src" "miri"];});
             |                                                                   ^
           33|       in {
```

I am using the overlay for the toolchain and compiling the rust binary with `crate2nix`. The error comes before `crate2nix` gets involved though. An excerpt of my flake.nix below.

```nix
{
system = "x86_64-linux";
target = "x86_64-mustang-linux-gnu";
overlays = [
  rust-overlay.overlays.default
  (self: super: let
    rust = super.rust-bin.selectLatestNightlyWith (toolchain: toolchain.default.override {extensions = ["rust-src" "miri"];});
  in {
    rustc = rust;
    cargo = rust;
  })
];

pkgs = import nixpkgs {
  inherit system overlays;
  crossSystem = {
    inherit system;
    rustc = {
      config = target;
      platform = builtins.fromJSON "${mustangTargets}/${target}.json";
    };
  };
};

generatedRustBuild = let
  buildRustCrateForPkgs = pkgs:
    pkgs.buildRustCrate.override {
      defaultCrateOverrides =
        pkgs.defaultCrateOverrides
        // {
          exmap = attrs: {
            NIX_CFLAGS_COMPILE = compileFlags;
            buildInputs = [pkgs.rustPlatform.bindgenHook exmapModule.dev];
          };
        };
    };
in
  pkgs.callPackage ./Cargo.nix {
    inherit buildRustCrateForPkgs;
  };

snowfalldb =
  generatedRustBuild
  .rootCrate
  .build;
}
```

**Comment by alekseysidorov** [comment]
You can change the Rust compilation target by setting some environment variables. 

I already did it in my [overlay](https://github.com/alekseysidorov/nixpkgs-cross-overlay): see the [rust-cross-hook.sh](https://github.com/alekseysidorov/nixpkgs-cross-overlay/blob/main/lib/hooks/rust-cross-hook.sh) and [`rustCrossHook.sh`](https://github.com/alekseysidorov/nixpkgs-cross-overlay/blob/main/lib/hooks/rustCrossHook.nix) contents

So I have a usage example [repository](https://github.com/alekseysidorov/nixpkgs-rust-service-example).

**Comment by oxalica** [comment]
> ```nix
>   (self: super: let
>     rust = super.rust-bin.selectLatestNightlyWith (toolchain: toolchain.default.override {extensions = ["rust-src" "miri"];});
>   in {
>     rustc = rust;
>     cargo = rust;
>   })
> ```

Please do NOT override the root attribute `rustc` and `cargo`. It would cause every dependent drvs to be rebuilt, and it seems to have weird interaction with package splicing.

I'm assuming you want a rustc which runs on `x86_64-linux` and compiles to `x86_64-mustang-linux-gnu`, that is `buildPackages.rust-bin.<..>` under your `crossSystem` configuration. So the compiler drv should be like this:

```nix
with import <nixpkgs> {
  system = "x86_64-linux";
  crossSystem = {
    system = "x86_64-linux";
    rustc = {
      config = "x86_64-mustang-linux-gnu";
      platform = throw "platform";
      # platform = ./platform.json; # builtins.fromJSON "${mustangTargets}/${target}.json";
    };
  };
  overlays = [ (import ./.) ];
};
buildPackages.rust-bin.selectLatestNightlyWith (toolchain: toolchain.default)
```

Unfortunately, it does not evaluate, but at least it gives the correct error message:
```
       error: Component resolution failed for rust-default-1.72.0-nightly-2023-06-05
       Unknown target `x86_64-mustang-linux-gnu`, typo or not supported by this version?
       note: profile components: rustc cargo rust-std rust-mingw rust-docs rustfmt-preview clippy-preview
       note: selected targets: x86_64-unknown-linux-gnu x86_64-mustang-linux-gnu
       note: components available for x86_64-unknown-linux-gnu: cargo clippy clippy-preview llvm-tools llvm-tools-preview miri miri-preview reproducible-artifacts rls rls-preview rust rust-analysis rust-analyzer rust-analyzer-preview rust-docs rust-docs-json rust-docs-json-preview rust-src rust-std rustc rustc-dev rustc-docs rustfmt rustfmt-preview
       note: check here to see all targets and which components are available on each targets:
             https://rust-lang.github.io/rustup-components-history
```

Since `rust-std` is a required component even for `minimal` profile, and there is no precompiled std for `x86_64-mustang-linux-gnu`, it does not work. My suggestion is to use normal non-cross-compiling `x86_64-linux` platform, and manually build your `std` via [`-Zbuild-std`](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std).

Sorry but we do not and will not implement drvs for building rustc or std from source.
