### ISSUE TITLE
build ERROR: at nixos, rust-bin.stable.latest.default ... libgcc_s.so.1 -> not found!

### ISSUE THREAD

**Issue by PlumpMath** [oxalica/rust-overlay#123]
building the system configuration...
error: builder for '/nix/store/32kfygmifnz00y1yplvhgi7zjy8gv5qk-cargo-1.66.1-x86_64-unknown-linux-gnu.drv' failed with exit code 1;
       last 10 log lines:
       > searching for dependencies of /nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu/bin/cargo
       >     libgcc_s.so.1 -> not found!
       > auto-patchelf: 2 dependencies could not be satisfied
       > error: auto-patchelf could not satisfy dependency libgcc_s.so.1 wanted by /nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu/libexec/cargo-credential-1password
       > error: auto-patchelf could not satisfy dependency libgcc_s.so.1 wanted by /nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu/bin/cargo
       > auto-patchelf failed to find all the required dependencies.
       > Add the missing dependencies to --libs or use `--ignore-missing="foo.so.1 bar.so etc.so"`.
       > /nix/store/aa283g93zqf3111m66kawl6d5z3wlawd-stdenv-linux/setup: line 79: pop_var_context: head of shell_variables not a function context
       > /nix/store/aa283g93zqf3111m66kawl6d5z3wlawd-stdenv-linux/setup: line 1457: pop_var_context: head of shell_variables not a function context
       > /nix/store/aa283g93zqf3111m66kawl6d5z3wlawd-stdenv-linux/setup: line 1594: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix log /nix/store/32kfygmifnz00y1yplvhgi7zjy8gv5qk-cargo-1.66.1-x86_64-unknown-linux-gnu.drv'.
error: 1 dependencies of derivation '/nix/store/q05dc90ddxnpxsxqvkbmlgxprci3s0ga-rust-default-1.66.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/cg9rcxy6w5sxsmdvv60gikhazsn0p0ad-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/3vwnvvk1wad111knm1wfw76s5zakfccr-set-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jljz4xc5fn288qlmz8f8kkgg38xirpy3-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/g7n76ng89kfn9s681qvqbq1yidz7960w-nixos-system-nuc-23.05.20230415.85b0815.drv' failed to build

**Comment by PlumpMath** [comment]
nix log /nix/store/32kfygmifnz00y1yplvhgi7zjy8gv5qk-cargo-1.66.1-x86_64-unknown-linux-gnu.drv


@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/b3iq4w5rhbdsc3gid1djd9cjpdybgk25-cargo-1.66.1-x86_64-unknown-linux-gnu.tar.xz
source root is cargo-1.66.1-x86_64-unknown-linux-gnu
setting SOURCE_DATE_EPOCH to timestamp 1673388313 of file cargo-1.66.1-x86_64-unknown-linux-gnu/version
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "installPhase" }
installing
Installing component cargo
@nix { "action": "setPhase", "phase": "fixupPhase" }
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu
shrinking /nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu/libexec/cargo-credential-1password
shrinking /nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu/bin/cargo
checking for references to /build/ in /nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu...
gzipping man pages under /nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu/share/man/
patching script interpreter paths in /nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu
automatically fixing dependencies for ELF files
{'ignore_missing': [],
 'libs': [PosixPath('/nix/store/lcfhnr6wrj9ssd3dxs39sprvz6qrxlj5-gnutar-1.34/lib'),
          PosixPath('/nix/store/vs77f36ak1rbwnpy4kxxpwagpyxqxjvl-auto-patchelf-hook/lib'),
          PosixPath('/nix/store/qpxdvk9a5nvgvm0vvmfikgf4cdmfjxcn-binutils-wrapper-2.40/lib'),
          PosixPath('/nix/store/2y0q33dmn7846bpqcnfch4a0q2q6dmya-patchelf-0.15.0/lib'),
          PosixPath('/nix/store/h9lc1dpi14z7is86ffhl3ld569138595-audit-tmpdir.sh/lib'),
          PosixPath('/nix/store/m54bmrhj6fqz8nds5zcj97w9s9bckc9v-compress-man-pages.sh/lib'),
          PosixPath('/nix/store/wgrbkkaldkrlrni33ccvm3b6vbxzb656-make-symlinks-relative.sh/lib'),
          PosixPath('/nix/store/5yzw0vhkyszf2d179m0qfkgxmp5wjjx4-move-docs.sh/lib'),
          PosixPath('/nix/store/fyaryjvghbkpfnsyw97hb3lyb37s1pd6-move-lib64.sh/lib'),
          PosixPath('/nix/store/kd4xwxjpjxi71jkm6ka0np72if9rm3y0-move-sbin.sh/lib'),
          PosixPath('/nix/store/pag6l61paj1dc9sv15l7bm5c17xn5kyk-move-systemd-user-units.sh/lib'),
          PosixPath('/nix/store/bxsly8a56yb8kyrq03s82a3vyc8fqrb3-multiple-outputs.sh/lib'),
          PosixPath('/nix/store/nf1lkdrhapsx5lr6diyxyjr7pb7r20gr-patch-shebangs.sh/lib'),
          PosixPath('/nix/store/cickvswrvann041nqxb0rxilc46svw1n-prune-libtool-files.sh/lib'),
          PosixPath('/nix/store/xyff06pkhki3qy1ls77w10s0v79c9il0-reproducible-builds.sh/lib'),
          PosixPath('/nix/store/ngg1cv31c8c7bcm2n8ww4g06nq7s4zhm-set-source-date-epoch-to-latest.sh/lib'),
          PosixPath('/nix/store/d275wzmimzi3xp4j3vbkvxscmc79q088-strip.sh/lib'),
          PosixPath('/nix/store/lf6arf2qj94qs6bkzfl2y75chb7awmx9-zlib-1.2.13-dev/lib'),
          PosixPath('/nix/store/2ldgh1qis9p4zf8bgsdm7897gw8vv36g-zlib-1.2.13/lib'),
          PosixPath('/nix/store/lcfhnr6wrj9ssd3dxs39sprvz6qrxlj5-gnutar-1.34/lib'),
          PosixPath('/nix/store/vs77f36ak1rbwnpy4kxxpwagpyxqxjvl-auto-patchelf-hook/lib'),
          PosixPath('/nix/store/qpxdvk9a5nvgvm0vvmfikgf4cdmfjxcn-binutils-wrapper-2.40/lib'),
          PosixPath('/nix/store/2y0q33dmn7846bpqcnfch4a0q2q6dmya-patchelf-0.15.0/lib'),
          PosixPath('/nix/store/h9lc1dpi14z7is86ffhl3ld569138595-audit-tmpdir.sh/lib'),
          PosixPath('/nix/store/m54bmrhj6fqz8nds5zcj97w9s9bckc9v-compress-man-pages.sh/lib'),
          PosixPath('/nix/store/wgrbkkaldkrlrni33ccvm3b6vbxzb656-make-symlinks-relative.sh/lib'),
          PosixPath('/nix/store/5yzw0vhkyszf2d179m0qfkgxmp5wjjx4-move-docs.sh/lib'),
          PosixPath('/nix/store/fyaryjvghbkpfnsyw97hb3lyb37s1pd6-move-lib64.sh/lib'),
          PosixPath('/nix/store/kd4xwxjpjxi71jkm6ka0np72if9rm3y0-move-sbin.sh/lib'),
          PosixPath('/nix/store/pag6l61paj1dc9sv15l7bm5c17xn5kyk-move-systemd-user-units.sh/lib'),
          PosixPath('/nix/store/bxsly8a56yb8kyrq03s82a3vyc8fqrb3-multiple-outputs.sh/lib'),
          PosixPath('/nix/store/nf1lkdrhapsx5lr6diyxyjr7pb7r20gr-patch-shebangs.sh/lib'),
          PosixPath('/nix/store/cickvswrvann041nqxb0rxilc46svw1n-prune-libtool-files.sh/lib'),
          PosixPath('/nix/store/xyff06pkhki3qy1ls77w10s0v79c9il0-reproducible-builds.sh/lib'),
          PosixPath('/nix/store/ngg1cv31c8c7bcm2n8ww4g06nq7s4zhm-set-source-date-epoch-to-latest.sh/lib'),
          PosixPath('/nix/store/d275wzmimzi3xp4j3vbkvxscmc79q088-strip.sh/lib'),
          PosixPath('/nix/store/lf6arf2qj94qs6bkzfl2y75chb7awmx9-zlib-1.2.13-dev/lib'),
          PosixPath('/nix/store/2ldgh1qis9p4zf8bgsdm7897gw8vv36g-zlib-1.2.13/lib')],
 'paths': [PosixPath('/nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu')],
 'recursive': True,
 'runtime_dependencies': []}
setting interpreter of /nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu/libexec/cargo-credential-1password
searching for dependencies of /nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu/libexec/cargo-credential-1password
    libgcc_s.so.1 -> not found!
setting interpreter of /nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu/bin/cargo
searching for dependencies of /nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu/bin/cargo
    libgcc_s.so.1 -> not found!
auto-patchelf: 2 dependencies could not be satisfied
error: auto-patchelf could not satisfy dependency libgcc_s.so.1 wanted by /nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu/libexec/cargo-credential-1pass
word
error: auto-patchelf could not satisfy dependency libgcc_s.so.1 wanted by /nix/store/9872fk2mpwxdyqd3h1xn2jzr696mp89n-cargo-1.66.1-x86_64-unknown-linux-gnu/bin/cargo
auto-patchelf failed to find all the required dependencies.
Add the missing dependencies to --libs or use `--ignore-missing="foo.so.1 bar.so etc.so"`.
/nix/store/aa283g93zqf3111m66kawl6d5z3wlawd-stdenv-linux/setup: line 79: pop_var_context: head of shell_variables not a function context
/nix/store/aa283g93zqf3111m66kawl6d5z3wlawd-stdenv-linux/setup: line 1457: pop_var_context: head of shell_variables not a function context
/nix/store/aa283g93zqf3111m66kawl6d5z3wlawd-stdenv-linux/setup: line 1594: pop_var_context: head of shell_variables not a function context
(END)

**Comment by oxalica** [comment]
Should be fixed in c949d341f2b507857d589c48d1bd719896a2a224. Have you tried to update to the latest commit of rust-overlay?

**Comment by PlumpMath** [comment]
nix flake update --show-trace

...

• Updated input 'rust-overlay/flake-utils':
    follows 'flake-utils'
  → 'github:numtide/flake-utils/cfacdce06f30d2b68473a46042957675eebb3401' (2023-04-11)
• Added input 'rust-overlay/flake-utils/systems':
    'github:nix-systems/default/da67096a3b9bf56a91d16901293e51ba5b49a27e' (2023-04-09)
• Updated input 'rust-overlay/nixpkgs':
    follows 'nixpkgs'
  → 'github:NixOS/nixpkgs/b605a205390e53e18c03329ab3dba489970c1e0a' (2023-04-16)
  
  ...
  
error: builder for '/nix/store/ig2kcg4c457l43bqm5ggck73241i7hik-cargo-1.68.0-nightly-2023-01-12-x86_64-unknown-linux-gnu.drv' failed with exit code 1;


I will look into whether there is an issue with my Nixpkgs configuration in my NixOS. I have been using the latest commit, but there may be some issues with NixOS. I have also tried switching to nightly, but the issue remains the same. 

Thank you.

**Comment by oxalica** [comment]
Please provide your `flake.nix`, `flake.lock`, and the code causing the issue.

**Comment by PlumpMath** [comment]
I figured out the reason for the error. It was the cargo2nix overlay causing the issue. Your hint was helpful in performing the surgery to resolve it. :))

**Comment by PlumpMath** [comment]
@tcoopman 

I solved this problem by removing cargo2nix, which caused issues during installation.
