### ISSUE TITLE
rustup not found after home-manager installation

### ISSUE THREAD

**Issue by sukhmel** [oxalica/rust-overlay#126]
I'm very new to NixOS, so it might be something simple, but right now I can't install rust via the overlay in home-manager:

1. I am using [nix-darwin](https://github.com/LnL7/nix-darwin)
2. overlay is imported as a flake
3. it is then added to nixpkgs.overlays inside of home-manager loading (?) function:

       darwinConfigurations =
       let
         system = "aarch64-darwin";
       in builtins.listToAttrs (map
         (host: {
           name = host;
 
           value = darwin.lib.darwinSystem {
             system = system; 

             modules = [
               (./machines + "/${system}/${host}/configuration.nix")
               home-manager.darwinModules.home-manager
               {
                 nixpkgs.overlays = [ rust-overlay.overlays.default ];
 
                 home-manager.verbose = true;
                 home-manager.useUserPackages = true;
                 home-manager.users.sukhmel = self.homeConfigurations.desktop;
               }
             ];
           };
         })
         (builtins.attrNames (builtins.readDir ./machines/${system})));

4. in `configuration.nix` I have a part that adds rust to systemPackages:

        environment.systemPackages = with pkgs; [
            ...
            (rust-bin.fromRustupToolchainFile ../../../rust-toolchain.toml)
        ]
5. If I load the flake with `nix repl` and queury contents of `outputs.darwinConfigurations.mbp-m1-vladislav.pkgs.rustup` it outputs `«derivation /nix/store/9ks1g5my158hvd4ii8w4vb0fk6qq29vz-rustup-1.25.1.drv»`
6. But the rustup can't be found when this configuration is applied with `darwin-rebuild switch --flake .`

If instead of `(rust-bin.fromRustupToolchainFile ../../../rust-toolchain.toml)` I use `rustup`, it becomes accessible as it should

**Comment by oxalica** [comment]
> I use `rustup`.

`rustup` is not part of Rust toolchain, but a toolchain manager. We don't have `rustup`. We do its jobs and are replacing it.

If you prefer a typical `rustup` workflow, you can install it from nixpkgs without rust-overlay.

**Comment by sukhmel** [comment]
Well, it was a misunderstanding then, sorry to bother.
