### ISSUE TITLE
Having rustc, rust-src and cargo in the same path

### ISSUE THREAD

**Issue by donni-h** [oxalica/rust-overlay#127]
Hey there,
I'm still new to Nix so please go lightly on me! :)

I wanted to create a Rust project with Nix, and tried instantiating it with rust-overlay.
That worked pretty well, but since I'm using intellij and intellij-rust it expects both rustc, and cargo to be in the same target directory so that it can properly detect the two.
Is there a way to use rust-overlay and still have my desired behaviour?
Thanks in advance! :)

**Comment by oxalica** [comment]
> it expects both rustc, and cargo to be in the same target directory

[All common usages](https://github.com/oxalica/rust-overlay#cheat-sheet-common-usage-of-rust-bin), eg. `rust-bin.stable.latest.default`, should be like that. It collects all components into one derivation/directory via symlinks (mostly).

I don't use intellij. You can try it out.
