### ISSUE TITLE
Installation instructions for Nix overlay cause error "expression does not evaluate to a derivation"

### ISSUE THREAD

**Issue by mtesseract** [oxalica/rust-overlay#131]
Hi,

I'm trying to install this rust-overlay on a nix-darwin system. I am following this piece of the documentation:

> Classic Nix overlay
> 
> You can put the code below into your ~/.config/nixpkgs/overlays.nix.
> 
> ```
> [ (import (builtins.fetchTarball "https://github.com/oxalica/rust-overlay/archive/master.tar.gz")) ]
> ```
> Then the provided attribute paths are available in nix command.
> ```
> $ nix-env -iA rust-bin.stable.latest.default # Do anything you like.
> ```

I have added the above overlay reference into my `~/.config/nixpkgs/overlays.nix`, but the example `nix-env` command fails with:
```
error: attribute 'rust-bin' in selection path 'rust-bin.stable.latest.default' not found
```

Furthermore, when doing something:
```
$ nix-env -vqaP '*' 
```

the command fails with the following (shortened) output:
```
[...]
evaluating file '/nix/store/pvfv4fw2w5zx7jxrn8ph914jar85jbnx-rust-overlay/rust-overlay/default.nix'
error: expression does not evaluate to a derivation (or a set or list of those)
```

As far as I can tell the content of the directory `/nix/store/pvfv4fw2w5zx7jxrn8ph914jar85jbnx-rust-overlay/rust-overlay` seems reasonable:

```
$ ls /nix/store/pvfv4fw2w5zx7jxrn8ph914jar85jbnx-rust-overlay/rust-overlay/ 
LICENSE    cargo-miri-wrapper.sh*  docs/      flake.lock  manifest.nix  mk-aggregated.nix     repl.nix          scripts/
README.md  default.nix             examples/  flake.nix   manifests/    mk-component-set.nix  rust-overlay.nix  tests/
```

`nix-info` says:

```
system: "aarch64-darwin", multi-user?: yes, version: nix-env (Nix) 2.15.0, channels(root): "darwin, home-manager-23.05.tar.gz, nixpkgs-23.05", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixpkgs
```

Is there anything wrong on my side or is the documentation outdated? Any help appreciated, I would like to get this overlay working.

Thank you
Moritz

**Comment by mtesseract** [comment]
Have to correct myself:

The above `nix-env` errors were caused by following **this** part of the docs:

> Alternatively, you can install it into nix channels.
> 
> ```
> $ nix-channel --add https://github.com/oxalica/rust-overlay/archive/master.tar.gz rust-overlay
> $ nix-channel --update
> ```

that is, adding the overlay as a separate channel.

When attempting to use it as a classic overlay configured via `overlays.nix`, it doesn't seem to produce any effect:

```
$ nix-env -iA rust-bin.stable.latest.default
error: attribute 'rust-bin' in selection path 'rust-bin.stable.latest.default' not found
```

**Comment by oxalica** [comment]
I don't quite understand which way you are trying.

1. If you set it up via nix-channel, you are supposed to instantiate a nixpkgs with rust-overlay via `import <nixpkgs> { overlays = [ (import <rust-overlay>) ]; }`. It must be explicitly imported, and nix-env does not automatically work.
2. If you set it up via `~/.config/nixpkgs/overlays.nix`, you are supposed to do it via `import <nixpkgs> {}`. And nix-env works in this case: `nix-env -iA rust-bin.stable.latest.default`.

**Comment by mtesseract** [comment]
Please excuse the confusion regarding the two different methods. Let's focus on the `overlays.nix` method for now (your method "2") -- I am still unable to configure it correctly and would greatly appreciate any help.

The [installation instructions](https://github.com/oxalica/rust-overlay#classic-nix-overlay) state this:

> You can put the code below into your ~/.config/nixpkgs/overlays.nix.
> 
> ```
> [ (import (builtins.fetchTarball "https://github.com/oxalica/rust-overlay/archive/master.tar.gz")) ]
> ```

In order to avoid a channel name collision (warning: name collision in input Nix expressions, skipping '/Users/moritz/.nix-defexpr/channels_root/nixpkgs'
suggestion: remove 'nixpkgs' from either the root channels or the user channels) I am now  trying this out as root user on nix-darwin. I have the following channels configured:

```
$ nix-channel --list
darwin https://github.com/LnL7/nix-darwin/archive/master.tar.gz
home-manager https://github.com/nix-community/home-manager/archive/release-23.05.tar.gz
nixpkgs https://nixos.org/channels/nixos-23.05
```

According to the documentation I did the following:
```
$ echo '[ (import (builtins.fetchTarball "https://github.com/oxalica/rust-overlay/archive/master.tar.gz")) ]' > ~/.config/nixpkgs/overlays.nix
```

Now `nix-env` fails:
```
$ nix-env -iA rust-bin.stable.latest.default
error: attribute 'rust-bin' in selection path 'rust-bin.stable.latest.default' not found
```

Maybe I need to update the channels first?
```
$ nix-channel --update
unpacking channels...
$ nix-env -iA rust-bin.stable.latest.default
error: attribute 'rust-bin' in selection path 'rust-bin.stable.latest.default' not found
$
```

That wasn't it, it seems.

Now, what confuses me in your reply is the following:

> [...] you are supposed to do it via `import <nixpkgs> {}`. And `nix-env` works in this case: `nix-env -iA rust-bin.stable.latest.default`.

Where is this (`import <nixpkgs> {}`) contained in the installation instructions (https://github.com/oxalica/rust-overlay#classic-nix-overlay)? Or is this somehow implicit knowledge?

Am I supposed to fill `~/.config/nixpkgs/overlays.nix` with something along the following lines?

```
import <nixpkgs> {
  overlays = [ (import (builtins.fetchTarball "https://github.com/oxalica/rust-overlay/archive/master.tar.gz")) ];
}
```

What *exactly* is `overlays.nix` supposed to contain? I have tried the above with no luck, it yields the same failure when calling `nix-env` to locate the rust packages.

Thanks for your help
Moritz

**Comment by oxalica** [comment]
> In order to avoid a channel name collision (warning: name collision in input Nix expressions, skipping '/Users/moritz/.nix-defexpr/channels_root/nixpkgs'
> suggestion: remove 'nixpkgs' from either the root channels or the user channels)

Seems you have a `nixpkgs` channel on root and a `nixpkgs` channel on your user, and Nix warns you 

> I am now trying this out as root user on nix-darwin.

Please only `sudo` on `nix-channel --update`. Do not run `nix-env` using root (`sudo`, etc), it would not be able to access your home overlay setup.

> Where is this (`import <nixpkgs> {}`) contained in the installation instructions (https://github.com/oxalica/rust-overlay#classic-nix-overlay)? Or is this somehow implicit knowledge?

I'm making an example about what do "installed overlays" affect: it should be injected automatically whenever you import nixpkgs in any Nix files (in impure mode, which is the default of `nix-env`).

> Am I supposed to fill ~/.config/nixpkgs/overlays.nix with something along the following lines?
> import <nixpkgs> {
>   overlays = [ (import (builtins.fetchTarball "https://github.com/oxalica/rust-overlay/archive/master.tar.gz")) ];
> }
> What exactly is overlays.nix supposed to contain? I have tried the above with no luck, it yields the same failure when calling nix-env to locate the rust packages.

No. `overlays.nix` should contains exactly one list expression, containing one or more overlay functions. One overlay function is like `final: prev: { /*...*/ }` like in [our entry Nix file](https://github.com/oxalica/rust-overlay/blob/fc57a011f1c20d2b24f75a79ab669430a221b220/default.nix).

Please also read the Overlays chapter in nixpkgs manual: https://nixos.org/manual/nixpkgs/stable/#sec-overlays-lookup

> According to the documentation I did the following:
> 
> $ echo '[ (import (builtins.fetchTarball "https://github.com/oxalica/rust-overlay/archive/master.tar.gz")) ]' > ~/.config/nixpkgs/overlays.nix
> 
> Now nix-env fails:
> 
> $ nix-env -iA rust-bin.stable.latest.default
> error: attribute 'rust-bin' in selection path 'rust-bin.stable.latest.default' not found

That's strange. Could you execute each following command and paste their results? Except that sudo one, others run under your user.
- `nix-channel --list`
- `sudo nix-channel --list`
- `echo $NIX_PATH`
- `nix-instantiate --eval --expr __nixPath`
- `nix-instantiate --eval --expr '(import <nixpkgs> {}) ? rust-bin'`

**Comment by mtesseract** [comment]
> > In order to avoid a channel name collision (warning: name collision in input Nix expressions, skipping '/Users/moritz/.nix-defexpr/channels_root/nixpkgs'
> > suggestion: remove 'nixpkgs' from either the root channels or the user channels)
> 
> Seems you have a `nixpkgs` channel on root and a `nixpkgs` channel on your user, and Nix warns you

This is correct. I have been trying out multiple things out of non-familiarity with Nix. In order to avoid any unforeseen complications with the Nix channel & overlay setup in a multi-user environment  I did some experiments as root. But ultimately I would like to have the whole overlay setup in my user account.

> > I am now trying this out as root user on nix-darwin.
> 
> Please only `sudo` on `nix-channel --update`. Do not run `nix-env` using root (`sudo`, etc), it would not be able to access your home overlay setup.

For these experiments I even copied the `overlays.nix` to `~root/.config/nixpkgs/overlays.nix`.

> I'm making an example about what do "installed overlays" affect: it should be injected automatically whenever you import nixpkgs in any Nix files (in impure mode, which is the default of `nix-env`).

Ok, thanks, got it.

> Please also read the Overlays chapter in nixpkgs manual: https://nixos.org/manual/nixpkgs/stable/#sec-overlays-lookup

Thanks, seems helpful.

> > According to the documentation I did the following:
> > $ echo '[ (import (builtins.fetchTarball "https://github.com/oxalica/rust-overlay/archive/master.tar.gz")) ]' > ~/.config/nixpkgs/overlays.nix
> > Now nix-env fails:
> > $ nix-env -iA rust-bin.stable.latest.default
> > error: attribute 'rust-bin' in selection path 'rust-bin.stable.latest.default' not found
> 
> That's strange. Could you execute each following command and paste their results? Except that sudo one, others run under your user.
> 
> * `nix-channel --list`
> * `sudo nix-channel --list`
> * `echo $NIX_PATH`
> * `nix-instantiate --eval --expr __nixPath`
> * `nix-instantiate --eval --expr '(import <nixpkgs> {}) ? rust-bin'`

Sure, here it goes:

```
$ whoami     
moritz

$ nix-channel --list
nixpkgs https://nixos.org/channels/nixos-23.05

$ sudo nix-channel --list
warning: $HOME ('/Users/moritz') is not owned by you, falling back to the one defined in the 'passwd' file ('/var/root')
darwin https://github.com/LnL7/nix-darwin/archive/master.tar.gz
home-manager https://github.com/nix-community/home-manager/archive/release-23.05.tar.gz
nixpkgs https://nixos.org/channels/nixos-23.05

$ echo $NIX_PATH
/Users/moritz/.nix-defexpr/channels:darwin-config=/Users/moritz/.nixpkgs/darwin-configuration.nix:/nix/var/nix/profiles/per-user/root/channels

$ nix-instantiate --eval --expr __nixPath
[ { path = "/Users/moritz/.nix-defexpr/channels"; prefix = ""; } { path = "/Users/moritz/.nixpkgs/darwin-configuration.nix"; prefix = "darwin-config"; } { path = "/nix/var/nix/profiles/per-user/root/channels"; prefix = ""; } ]

$ nix-instantiate --eval --expr '(import <nixpkgs> {}) ? rust-bin'
true

$ nix-env -iA rust-bin.stable.latest.default
warning: name collision in input Nix expressions, skipping '/Users/moritz/.nix-defexpr/channels_root/nixpkgs'
suggestion: remove 'nixpkgs' from either the root channels or the user channels
error: attribute 'rust-bin' in selection path 'rust-bin.stable.latest.default' not found

$ 
```

Anything else I can do to help analysing this?

Moritz

**Comment by mtesseract** [comment]
Hi. Is there anything else I can provide for fixing this? I have tried again just a few days ago (with updated channels), but I am still running into the same issue: rust packages cannot be found with nix.

Thanks you.
Moritz

**Comment by oxalica** [comment]
Sorry I'm not sure what's causing the issue exactly. I cannot reproduce and don't have a darwin platform.

According to your last results, `nix-instantiate` did find `rust-bin` correctly, while `nix-env` did not. Maybe you can `nix-channel --remove nixpkgs` as your user and try again. Since `nix-env` blames that your user channel `nixpkgs` collides with root channel `nixpkgs`. If still not working, I have no idea. Maybe someone else could help.

**Comment by oxalica** [comment]
Wait, could you try `nix-env -iA nixpkgs.rust-bin.stable.latest.default` ?

**Comment by mtesseract** [comment]
> Wait, could you try `nix-env -iA nixpkgs.rust-bin.stable.latest.default` ?

Thank you!
That seems to be working. Do you happen to understand where this discrepancy in referencing the package attributes comes from (in particular since I have been following the setup instructions closely)?

Moritz
