### ISSUE TITLE
How to access rust-docs?

### ISSUE THREAD

**Issue by iwinux** [oxalica/rust-overlay#135]
Hi,

rust-overlay installs the `rust-docs` component by default. However, there's no obvious way to access it, other than looking up its Nix store path and `open /nix/store/xxxxxx-rust-docs//share/doc/rust/html/index.html` ("Traditionally", it is accessible via `rustup doc`).

Any suggestions?

**Comment by oxalica** [comment]
Dup of #80. I don't think there is a better way than a user shortcut script or a browser bookmark. And `cargo` does not support generating std docs https://github.com/rust-lang/rfcs/issues/2324

Programmatically, the docs path is `file://$(rustc --print sysroot)/share/doc/rust/html`.

**Comment by iwinux** [comment]
Thanks for the tip. `open "$(rustc --print sysroot)/share/doc/rust/html/index.html"` works! Didn't know about `rustc --print sysroot` before.
