### ISSUE TITLE
using `stable` channel with `rustfmt` from `nightly`

### ISSUE THREAD

**Issue by DanConwayDev** [oxalica/rust-overlay#136]
Does rust-overlay enable using `rustfmt` from `nightly` whilst otherwise using the `stable` toolchain?

With `rustup` both toolchains can be installed and `nightly` can be targeted by running `cargo +nightly fmt`.

https://github.com/oxalica/rust-overlay/issues/56#issuecomment-958191168 alludes to merging toolchains but I am not clear how this would be achieved. 

Thanks for your efforts in creating and maintaining rust-overlay :)

**Comment by oxalica** [comment]
You can pick one component from nightly toolchain and use `lib.hiPrio` on it to override others.
```rust
[
  (lib.hiPrio rust-bin.nightly."2023-09-01".rustfmt)
  (rust-bin.stable.latest.default.override { /* default toolchain */ })
]
```

**Comment by spikespaz** [comment]
I have the same question and find myself unsatisfied with the answer.
```nix
      devShells = eachSystem (system:
        let pkgs = pkgsFor.${system};
        in {
          default = pkgs.mkShell {
            strictDeps = true;
            packages = with pkgs; [
              rust-bin.stable.latest.default.override
              (lib.hiPrio (rust-bin.selectLatestNightlyWith (toolchain:
                toolchain.minimal.override { extensions = [ "rustfmt" ]; })))
              pkg-config
              openssl
            ];
          };
        });
```

Obviously, that derivation would also overwrite `rustc`, `cargo`, and `rust-std` from stable with the nightly version.

I would like to stay up-to-date with the latest available nightly after every `nix flake lock --update-input rust-overlay`, and do not wish to specify a nightly release date.

**Comment by spikespaz** [comment]
I don't like what I ended up with because, as you said, it is possible that one of these components doesn't build with the latest nightly.

```nix
devShells = eachSystem (system:
  let pkgs = pkgsFor.${system};
  in {
    default = pkgs.mkShell {
      strictDeps = true;
      packages = with pkgs; [
        (rust-bin.stable.latest.minimal.override {
          extensions = [ "rust-docs" ];
        })
        (lib.hiPrio rust-bin.nightly.latest.clippy)
        (lib.hiPrio rust-bin.nightly.latest.rustfmt)
        (lib.hiPrio rust-bin.nightly.latest.rust-analyzer)
        pkg-config
        openssl
      ];
    };
  });
```

I'd like to see something like this:
```nix
(rust-bin.stable.latest.minimal.override {
  extensions = [ "rustfmt" ];
}).extensions.rustfmt
```

**Comment by DanConwayDev** [comment]
Thanks @oxalica. I have this working.

Like @spikespaz, I'd prefer not to pin a specific version of nightly and take advantage of `selectLatestNightlyWith` but that is icing on the cake.

**Comment by spikespaz** [comment]
When using `rust-analyzer` from `nightly.latest`, I see errors like "can't find crate for `std`".

**Comment by spikespaz** [comment]
Trying to handle nightly more properly, attempted this:
```nix
devShells = eachSystem (system:
  let pkgs = pkgsFor.${system};
  in {
    default = pkgs.mkShell {
      strictDeps = true;
      packages = with pkgs; [
        (lib.hiPrio (rust-bin.stable.latest.minimal.override {
          extensions = [ "rust-docs" "rust-analyzer" ];
        }))
        (rust-bin.selectLatestNightlyWith (toolchain:
          toolchain.minimal.override {
            extensions = [ "clippy" "rustfmt" ];
          }))

        pkg-config
        openssl
      ];
    };
  });
```

Same problem though.

**Comment by spikespaz** [comment]
Using stable `clippy`, and nightly `rustfmt` and `rust-analyzer` works. Sticking with my last attempt, but switched `extensions` around slightly.

**Comment by sveitser** [comment]
> I'd like to see something like this:
> 
> ```nix
> (rust-bin.selectLatestNightlyWith (toolchain:
>   toolchain.minimal.override { extensions = [ "rustfmt" ];
> })).extensions.rustfmt
> ```

@spikespaz There is `passthru.availableComponents` that seems to accomplish this, not sure if it's a good idea to use that though.

```
nightlyToolchain = pkgs.rust-bin.selectLatestNightlyWith (toolchain: toolchain.minimal.override {
  extensions = [ "rustfmt" ];
});
...
buildInputs = [
  nightlyToolchain.passthru.availableComponents.rustfmt
  ...
]
```

**Comment by NobbZ** [comment]
As I tend to use `packages = builtins.attrValues {inherit …;}` in my shells, I debugged this for quite a while today…

`hiPrio` and similar do not have an effect in `mkShell`, here the order of appearance in the `package` list is relevant.

You and as the order of the list here is basically alphabetically having `inherit rust rustfmt` always puts `rust` first.

I therefore had to solve this via `packages = [rustfmt] ++ builtins.attrValues {inherit rust;}`.

This is a simplified version of what I did to solve it (for me), to make it easier to solve for anyone (including me) finding this in the future.

**Comment by spikespaz** [comment]
@NobbZ I'm surprised you say that `lib.hiPrio` doesn't work, because IIRC some time ago that is exactly the change that made it work for me.

I have been using [this template] for quite some time now.

[this template]: https://github.com/spikespaz/flake-templates/blob/97b7fd315c406b473c9dad5b59dc1b2297aa7008/templates/rust-devshell/flake.nix#L33

**Comment by NobbZ** [comment]
From what I can tell, your version works because of the order. Stable rust and its components shadow what is in the nightly following it. If you swap those 2, you get a nightly rust, regardless of the prio set. If you would remove the prio, nothign would change.

While my `rustfmt` is simply `rustfmt = pkgs.lib.hiPrio pkgs.rust-bin.nightly.latest.rustfmt;` as I want to avoid pulling multiple `cargo` or `rustc` into my `PATH`.

Also, your stable rust uses `minimal` and doesn't ship a rustfmt because of that. That might be something to eventually change my stuff to.
