### ISSUE TITLE
How to use this in `buildRustPackage`?

### ISSUE THREAD

**Issue by Septias** [oxalica/rust-overlay#152]
I would like to build a package with `rustPlatform.buildRustPackage`. How can I do that, I can't manage to do it myself :/

**Comment by oxalica** [comment]
There's a section in nixpkgs manual showing the example usage of `makeRustPlatform`. See [here](https://nixos.org/manual/nixpkgs/stable/#using-rust-nightly-in-a-derivation-with-buildrustpackage) or [this permalink](https://github.com/NixOS/nixpkgs/blob/c81dee1ff8c017004d9821505808dca41752fe89/doc/languages-frameworks/rust.section.md?plain=1#L892).

**Comment by Septias** [comment]
Thanks :)
