### ISSUE TITLE
Getting a toolchain with debuginfo_level

### ISSUE THREAD

**Issue by happysalada** [oxalica/rust-overlay#154]
First of all, thank you for your work on rust-overlay!
the perfbook mentions https://nnethercote.github.io/perf-book/profiling.html#debug-info debuginfo_level for the rust std to include more information useful for profiling tools.
Is there any way to have it with rust-overlay ? I couldn't find anything in the reference, so just asking here.
Thank you again for providing this critical piece of software for rust and nix !

**Comment by oxalica** [comment]
> https://nnethercote.github.io/perf-book/profiling.html#debug-info debuginfo_level for the rust std to include more information useful for profiling tools.

It reads:

> The most reliable way around this is to *build your own version of the compiler and standard library*, following [these 
> instructions](https://github.com/rust-lang/rust), and adding the following lines to the config.toml file:
> ```
> [rust]
> debuginfo-level = 1
> ```

It's a configuration to "build your own" rust. See [here](https://github.com/rust-lang/rust/blob/1f8e824f111c972c9df8dbb378d87c33f67bbad4/config.example.toml#L527).

rust-overlay ships precompiled binaries from official rustup server and patch them for Nix use. We don't build rustc and std on our own, thus we are not able to change configurations for building std.
