### ISSUE TITLE
Change to use self-contained lld by default in rustup nightly artifacts breaks native linking

### ISSUE THREAD

**Issue by Nemo157** [oxalica/rust-overlay#168]
https://github.com/rust-lang/rust/issues/71515#issuecomment-2116969162 mentions that the next nightly will switch to using the self-contained `lld` by default instead of the system linker. Trying to do some pre-testing of this setup by manually enabling the new defaults in a project with a native dependency indicates that this causes issues with library loading (presumably something rpath related, but I've never dug into the details of how that is handled normally):

```console
> cargo rustc -- -Clink-self-contained=+linker -Clinker-flavor=gnu-lld-cc
   Compiling u2f-touch-detector v0.1.0 (/home/nemo157/sources/u2f-touch-detector)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.58s

> $CARGO_HOME/target/shared/x86_64-unknown-linux-gnu/debug/u2f-touch-detector --help
/run/user/1000/cargo-home/target/shared/x86_64-unknown-linux-gnu/debug/u2f-touch-detector: error while loading shared libraries: libudev.so.1: cannot open shared object file: No such file or directory
```

The PR linked from the tracking issue mentions that the workaround will be to use `-Zlinker-features=-lld`.

**Comment by szlend** [comment]
I assume we'll probably need to wrap `rust-lld`, similar to https://github.com/NixOS/nixpkgs/issues/24744#issuecomment-2094118403

**Comment by Nemo157** [comment]
I found out why, I use `cranelift` as my codegen backend [which disables default-active lld](https://github.com/rust-lang/rust/blob/f092f73c112914752d3290fbbbfa2271c78f1088/compiler/rustc_codegen_ssa/src/back/link.rs#L3113). Testing with that overridden successfully fails:

```console
> CARGO_PROFILE_DEV_CODEGEN_BACKEND=llvm cargo run -- --help
   Compiling u2f-touch-detector v0.1.0 (/home/nemo157/sources/u2f-touch-detector)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.61s
     Running `/run/user/1000/cargo-home/target/shared/x86_64-unknown-linux-gnu/debug/u2f-touch-detector --help`
/run/user/1000/cargo-home/target/shared/x86_64-unknown-linux-gnu/debug/u2f-touch-detector: error while loading shared libraries: libudev.so.1: cannot open shared object file: No such file or directory
```

**Comment by szlend** [comment]
The `wrap` function is fairly simple, maybe worth vendoring it:
```bash
wrap() {
  local dst="$1"
  local wrapper="$2"
  export prog="$3"
  export use_response_file_by_default=${if isCCTools then "1" else "0"}
  substituteAll "$wrapper" "$out/bin/$dst"
  chmod +x "$out/bin/$dst"
}
```

You could then reference the ld wrapper like so:
```bash
mv $out/bin/rust-lld $out/bin/.rust-lld-unwrapped
wrap $out/bin/rust-lld \
  ${pkgs.path + /pkgs/build-support/bintools-wrapper/ld-wrapper.sh} \
  $out/bin/.rust-lld-unwrapped
```

**Comment by oxalica** [comment]
> The `wrap` function is fairly simple, maybe worth vendoring it:

Thanks for the investment of the ld-wrapper. I ends up copying part of the wrapper implementation to make it actually work. I created #171 and it works for me now. I'm looking for tests and feedback from people involving here.
