### ISSUE TITLE
`nix flake show --all-systems --json --no-write-lock-file` fails on armv7a-linux

### ISSUE THREAD

**Issue by grahamc** [oxalica/rust-overlay#179]
Not sure what changed, but `nix flake show --all-systems --json --no-write-lock-file` is failing to evaluate since just after 07098b424d114cd2dddec40be8d5586da339fddc:

```
      evaluating 'packages.armv7a-linux'...
      error: 'packages.armv7a-linux' is not an attribute set
```

**Comment by oxalica** [comment]
It's caused by nixpkgs no longer expose `legacyPackages.armv7a-linux` anymore.

```console
$ nix eval github:NixOS/nixpkgs#legacyPackages --apply builtins.attrNames
[ "aarch64-darwin" "aarch64-linux" "armv5tel-linux" "armv6l-linux" "armv7l-linux" "i686-linux" "mipsel-linux" "powerpc64le-linux" "riscv64-linux" "x86_64-darwin" "x86_64-linux" ]
```

Probably we should follow systems `nixpkgs.lib.systems.flakeExposed` instead of maintained our own list, so it can keep in sync with nixpkgs.
