### ISSUE TITLE
`rust-lld` not found for wasm target

### ISSUE THREAD

**Issue by VoreckLukas** [oxalica/rust-overlay#181]
So i installed the wasm toolchain in my devshell like this:
```nix
        devShells.default = pkgs.mkShell {
          nativeBuildInputs = with pkgs; [
            rustc
            cargo
            (rust-bin.stable.latest.default.override { targets = [ "wasm32-unknown-unknown" ]; })
          ];
          buildInputs = with pkgs; [ trunk ];
        };
```
but when compiling my code (wether it is with trunk or by running cargo build with the wasm build flag) i get this error
```
error: linker `rust-lld` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `neuland_rs` (bin "neuland_rs") due to 1 previous error
```

**Comment by oxalica** [comment]
Cannot reproduce. It seems like a configuration issue.

> ```nix
>           nativeBuildInputs = with pkgs; [
>             rustc
>             cargo
>             (rust-bin.stable.latest.default.override { targets = [ "wasm32-unknown-unknown" ]; })
>           ];
> ```

You install `pkgs.rustc` and `pkgs.cargo` from nixpkgs on top of rust-bin's rustc and cargo and overriding it. That would not work. Please do:


> ```nix
>           nativeBuildInputs = with pkgs; [
>             (rust-bin.stable.latest.default.override { targets = [ "wasm32-unknown-unknown" ]; })
>           ];
> ```

**Comment by VoreckLukas** [comment]
Oh, those were leftovers from a previous version of the flake when I  didnt install the toolchain with the override. didnt realize it installed cargo and rustc for me
