### ISSUE TITLE
error: attribute '"1.79.0"' missing

### ISSUE THREAD

**Issue by sdankel** [oxalica/rust-overlay#185]
I'm getting this error for rust version 1.79.0. Any help would be appreciated.

https://github.com/FuelLabs/fuel.nix/actions/runs/10397407695/job/28793121145?pr=144

![image](https://github.com/user-attachments/assets/cf915864-d5f0-49cd-8ecb-a2f94ec6df06)

**Comment by oxalica** [comment]
According to your [`flake.lock`](https://github.com/FuelLabs/fuel.nix/blob/6edf241cfd5c52407704cc70c55d98266e5fef0f/flake.lock#L57), it is using a historical commit of rust-overlay 8ce81e71ab04a7e906fae62da086d6ee5d6cfc21 on 2024-03-14 which is earlier than rust 1.79.0. Please `nix flake update` to the latest.
