### ISSUE TITLE
Nixpkgs Rust build machinery no longer supports Cargo 1.38 and older

### ISSUE THREAD

**Issue by emilazy** [oxalica/rust-overlay#186]
Just a heads‐up that https://github.com/NixOS/nixpkgs/pull/331167 was merged, so as of Nixpkgs 24.11 it won’t be possible to use the Rust build machinery with stable versions before 1.39. It might be reasonable to consider dropping older stable releases if that’s a relevant consideration for you.

**Comment by oxalica** [comment]
Thanks for the information. We don't rely on nixpkgs's rust builders (`buildRust*`), so I don't think we are technically affected. Standalone rust toolchain installations and dev envs using rust-overlay should still work. Users of `rustPlatform` involving rust-overlay's toolchains will be affected, but there is nothing we could help in this case.
