### ISSUE TITLE
How do I use this to replace mozilla overlay in presence of rustup toolchain file?

### ISSUE THREAD

**Issue by Fuuzetsu** [oxalica/rust-overlay#21]
If we look at something like crate2nix, it's documented how to use mozilla overlay: https://github.com/kolloch/crate2nix#choosing-a-rust-version

What is done there is we generate the toolchain then override individual components like rustc and such in the nixpkgs.

However, `fromRustupToolchainFile` only produces a single derivation and individual components don't seem accessible. This is documented at https://discourse.nixos.org/t/rust-overlay-a-better-rust-toolchain-provider-and-drop-in-replacement-of-nixpkgs-mozilla/10986/14

I have something like this
```nix

let
  sources = import ./sources.nix;
  rustChannelsOverlay = import sources.rust-overlay;
  # rustChannelsSrcOverlay =
  #   import "${sources.nixpkgs-mozilla}/rust-src-overlay.nix";
in import sources.nixpkgs {
  overlays = [
    rustChannelsOverlay
    # rustChannelsSrcOverlay
    (self: super:
      let rustChannel = self.rust-bin.fromRustupToolchainFile ../rust-toolchain;
      in {
        rustc = rustChannel;
        cargo = rustChannel;
        # rust = rustChannel;
        rust-fmt = rustChannel;
        rust-std = rustChannel;
        clippy = rustChannel;
        # inherit (rustChannel) cargo rust rust-fmt rust-std clippy;
      })
  ];
}
```

and it kind of seems to be working (I haven't completely verified) but it seems a bit wrong somehow. Also `rust` attribute doesn't exist so it's probably going to do wrong with if we try to cross-compile or something.

**Comment by oxalica** [comment]
Using the returned derivation of `fromRustupToolchainFile` to override all components as you did should work since it is a `symlinkJoin` of all these components.
If you run into some errors (whether cross-compiling or not), please provide more details and steps to reproduce.
