### ISSUE TITLE
Forks of rustc

### ISSUE THREAD

**Issue by drozdziak1** [oxalica/rust-overlay#32]
How would I go about having rust-overlay build the toolchain from a custom source I choose? I wish to use the [Solana](https://github.com/solana-labs/rust) fork and it seems the `fromRustcRev` function isn't really meant for that.

**Comment by oxalica** [comment]
Sorry but we doesn't build rustc from source at all. We simply fetch official distributed binaries and patch them. It is not possible to build from custom `rustc` source in this project.
Maybe you can try to override `rustPlatform` in `nixpkgs`. But havn't checked if it would work.
