### ISSUE TITLE
Missing shared library when invoking `cargo objcopy`

### ISSUE THREAD

**Issue by mitchmindtree** [oxalica/rust-overlay#33]
Hi folks! I'm working on an embedded project, and so far this overlay has been great for setting up a custom rust installation with the necessary components etc.

However, I've just tried using `cargo objcopy -- -O binary` for the first time in preparation for flashing my rust program to some embedded hardware and am running into the following error:

```
1/nix/store/q8kjvbvac54g8q8hmxsp530iv87r47j5-rust-default-1.51.0/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-objcopy: error while loading shared libraries: libLLVM-11-rust-1.51.0-stable.so: cannot open shared object file: No such file or directory
```

Any idea on what might be going on here?

Going to try switching back to `rustup` temporarily to see if that still works.

**Comment by oxalica** [comment]
This should be fixed in #28. Please run `nix flake update` to update `rust-overlay` to latest commit and check it again.

**Comment by mitchmindtree** [comment]
Ahh thanks for the link! I'm not using flakes just yet but will try updating the git rev I'm using soon and report back.

**Comment by oxalica** [comment]
ping @mitchmindtree

**Comment by mitchmindtree** [comment]
Thanks for the reminder, can confirm updating seems to have solved this. Thanks!
