### ISSUE TITLE
Missing nightly components for `x86_64-unknown-linux-gnu` target

### ISSUE THREAD

**Issue by timothyklim** [oxalica/rust-overlay#34]
Greetings!

Since **2021-04-25** the profiles `default` and `complete` can not be used:

```
error: Component resolution failed for rust-complete-1.53.0-nightly-2021-04-29
       - note: available extensions are cargo, clippy, clippy-preview, llvm-tools-preview, miri, miri-preview, reproducible-artifacts, rls, rls-preview, rust-analysis, rust-analyzer-preview, rust-docs, rust-mingw, rust-src, rust-std, rustc, rustc-dev, rustc-docs, rustfmt, rustfmt-preview
       - Host component `rustfmt-preview` doesn't support target `x86_64-unknown-linux-gnu`
       - Host component `rls-preview` doesn't support target `x86_64-unknown-linux-gnu`
```

**Comment by a-kenji** [comment]
Hey! They didn't build for that nightly. So they are not available.

**Comment by timothyklim** [comment]
> Hey! They didn't build for that nightly. So they are not available.

Yeah, I know. How about to add new profile without `-preview` components?

**Comment by a-kenji** [comment]
That could be a solution. 
But didn't `normal` `rustfmt` also stop building for that nightly at first?

**Comment by timothyklim** [comment]
> That could be a solution.
> But didn't `normal` `rustfmt` also stop building for that nightly at first?

Normal `rustfmt` and `rls` still available.

**Comment by oxalica** [comment]
You can check here for availability of nightly components: https://rust-lang.github.io/rustup-components-history/
