### ISSUE TITLE
A flake example of picking nightly components would be great

### ISSUE THREAD

**Issue by gilescope** [oxalica/rust-overlay#43]
(Sorry nixos noob here) The selectLatestNightlyWith seems excellent, but I'm not quite sure how to call it. I tried this:
```
        buildInputs = [
            pkgs.openssl
            pkgs.pkgconfig
            pkgs.exa
            pkgs.rust-bin.selectLatestNightlyWith (toolchain: toolchain.default.override {
              extensions = [ "llvm-tools-preview" ];
            })
          ];
```
but it's saying function can't be string (I did say I was a noob!). It would be great to have an example usage as there's not currently one on the internet yet and it feel to me that this would be the best default nightly flake template for people to use.

**Comment by oxalica** [comment]
The usage should be correct. You just need parenthesis inside the list of `buildInputs`.
```nix
buildInputs = [
    pkgs.openssl
    pkgs.openssl
    pkgs.pkgconfig
    pkgs.exa
    # This is a function call, not two elements of `buildInputs`.
    (pkgs.rust-bin.selectLatestNightlyWith (toolchain: toolchain.default.override {
        extensions = [ "llvm-tools-preview" ];
    }))
];
```
