### ISSUE TITLE
`lib/rustlib/<arch>/bin/gcc-ld/ld` should be wrapped for `-Clinker-flavor=gcc-lld`

### ISSUE THREAD

**Issue by oxalica** [oxalica/rust-overlay#46]
The option is available on nightly now: https://github.com/rust-lang/rust/pull/85961
And it may be enabled by default on Ubuntu in the future: https://github.com/rust-lang/rust/issues/71515

Currently the `ld` executable (actually `lld`) runs but failed to find C libraries. It should to be wrapped by `wrapBintoolsWith`.

**Comment by 1000teslas** [comment]
Wait, so `-Z gcc-ld=lld` not working for C libraries might be a Nix thing, and not rustc in general?

**Comment by oxalica** [comment]
> Wait, so -Z gcc-ld=lld not working for C libraries might be a Nix thing, and not rustc in general?

It's not about C libraries. Currently it doesn't work for a simple rust hello world program, since std requires `-lc`.

> I tried -C link-arg=-fuse-ld=lld, which I think uses the nixpkgs lld

It may be another issue. Currently I'm using the `rust-lld` shipped by rust toolchain with some manual wrapping and it works fine with things like `openssl`. But of course, you still need `nix-shell -p openssl pkg-config` to let the build script find the library first.

**Comment by 1000teslas** [comment]
On my machine, using `-Z gcc-ld=lld` and `-C link-arg=-fuse-ld=lld` with the Rust from this overlay works for pure-Rust projects. Does it not work for you?

**Comment by oxalica** [comment]
> On my machine, using -Z gcc-ld=lld and -C link-arg=-fuse-ld=lld with the Rust from this overlay works for pure-Rust projects.

Oh yes, it seems working now. Weird.

I also tested `openssl` which links to C library. It also works fine in `nix-shell -p openssl pkg-config` environment.

**Comment by 1000teslas** [comment]
Hmm, that's strange. When I use a dependency with `openssl-sys`, say reqwest 0.11.4, I get this error when running a compiled program 

`target/debug/downloader: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`
