### ISSUE TITLE
Issue cross-compiling to Windows from NixOS

### ISSUE THREAD

**Issue by kognise** [oxalica/rust-overlay#52]
I'm trying to cross-compile a Rust project to Windows with MinGW. I'm getting the ungoogleable error "rust is no available" and I'm not sure what next steps to take.

This is the smallest `shell.nix` that can reproduce the problem:

```nix
let
  pkgs = import <nixpkgs> {
    crossSystem = { config = "x86_64-w64-mingw32"; };
    overlays = [
      (import (builtins.fetchTarball "https://github.com/oxalica/rust-overlay/archive/master.tar.gz"))
    ];
  };
in pkgs.mkShell { 
  nativeBuildInputs = [
    pkgs.buildPackages.rust-bin.stable.latest.rust
  ];
}
```

And the error message:

```
error: while evaluating the attribute 'nativeBuildInputs' of the derivation 'nix-shell-x86_64-w64-mingw32' at /nix/store/0qm06jcncxkn0ds17pawl0kpbj1m0cyi-nixos-21.05.3314.83413f47809/nixos/pkgs/stdenv/generic/make-derivation.nix:201:11:
while evaluating the attribute 'paths' of the derivation 'rust-1.55.0' at /nix/store/0qm06jcncxkn0ds17pawl0kpbj1m0cyi-nixos-21.05.3314.83413f47809/nixos/pkgs/stdenv/generic/make-derivation.nix:201:11:
while evaluating 'getComponents' at /nix/store/dspngfrg375swrfj5sbcags7chd01bbc-source/rust-overlay.nix:176:81, called from /nix/store/dspngfrg375swrfj5sbcags7chd01bbc-source/rust-overlay.nix:426:26:
while evaluating 'flatten' at /nix/store/0qm06jcncxkn0ds17pawl0kpbj1m0cyi-nixos-21.05.3314.83413f47809/nixos/lib/lists.nix:137:13, called from /nix/store/dspngfrg375swrfj5sbcags7chd01bbc-source/rust-overlay.nix:183:19:
while evaluating 'getTargetPkgTuples' at /nix/store/dspngfrg375swrfj5sbcags7chd01bbc-source/rust-overlay.nix:131:64, called from /nix/store/dspngfrg375swrfj5sbcags7chd01bbc-source/rust-overlay.nix:183:28:
while evaluating 'getExtensions' at /nix/store/dspngfrg375swrfj5sbcags7chd01bbc-source/rust-overlay.nix:109:34, called from /nix/store/dspngfrg375swrfj5sbcags7chd01bbc-source/rust-overlay.nix:136:20:
while evaluating the attribute 'target.x86_64-w64-windows-gnu' at /nix/store/dspngfrg375swrfj5sbcags7chd01bbc-source/manifest.nix:67:9:
while evaluating the attribute 'target."*"' at /nix/store/dspngfrg375swrfj5sbcags7chd01bbc-source/manifest.nix:67:9:
rust is no available
```

**Comment by oxalica** [comment]
It's an issue on nixos 21.05 that `rust.toRustTarget` works improperly for mingw targets. It works on nixpkgs master and unstable.

The expr `rust.toRustTarget pkgsCross.mingwW64.hostPlatform` returns `"x86_64-pc-windows-gnu"` on nixpkgs master and unstable, but on stable 21.05, it returns incorrect `"x86_64-w64-windows-gnu"`.

I opened a backport PR for 21.05. You can checkout and apply it on your nixpkgs. https://github.com/NixOS/nixpkgs/pull/139697

**Comment by oxalica** [comment]
Also note that the component `rust` is deprecated and may be removed in the future. You should already see an warning.
Please use profile name like `default` instead, which is `pkgs.buildPackages.rust-bin.stable.latest.default`.

**Comment by kognise** [comment]
Thank you-- after a bit more research I thought `toRustTarget` might've been the issue and saw the commit fixing it, but after switching channels the problem was still there. I may have somehow just switched incorrectly. 

And yeah, I know `rust` is deprecated but it was the simplest option while debugging. Thank you for the backport PR, and I appreciate the help!

**Comment by kognise** [comment]
I'm sorry, I have a bit of a dumb question. How can I get the correct version of Nixpkgs? `sudo nix-channel --update` and `sudo nixos-rebuild switch --upgrade` didn't seem to update the Rust derivation that this overlay uses, and pulling+importing a tarball of unstable in place of `<nixpkgs>` didn't help either,

Apologies to bother you, and feel free not to answer as I'm aware this is a bit out of scope for this project.

**Comment by oxalica** [comment]
> My shell.nix:

I use your shell.nix and `cargo build --target x86_64-pc-windows-gnu` successfully built the windows PE file for a simple hello world program.
Are you missing the target flag? Or maybe you specify the wrong linker in `.cargo/config` or `$CARGO_HOME/config`? It should work without any config.

Also if you specify the `crossSystem` for nixpkgs. You don't need to override `targets` with that target again. It will be automatically added.

**Comment by kognise** [comment]
I'm sorry, I forgot to include important information. Adding `miniz_oxide = "0.4"` to the dependencies triggers the issue when it builds. This is just a dependency of a different package I'm using but it's a smaller example.

And that's awesome, removed it!

**Comment by kognise** [comment]
I did some more experimenting. It looks like it isn't the dependency's fault either, simply creating a `build.rs` and adding `fn main() {}` triggers the issue.

**Comment by kognise** [comment]
I believe I narrowed it down as much as I can.

The build.rs is compiled with gcc so it runs on the current platform, and the rest of the project is compiled with mingw.

The NIX_LDFLAGS contains the windows version of the pthreads library which gcc doesn't understand. If I manually remove it, then mingw doesn't understand the built-in linux version.

**Comment by oxalica** [comment]
> The NIX_LDFLAGS contains the windows version of the pthreads library which gcc doesn't understand. If I manually remove it, then mingw doesn't understand the built-in linux version.

I think you could report this issue to `nixpkgs`.

**Comment by kognise** [comment]
That sounds *fun*! Thanks for the time.
