### ISSUE TITLE
Cross-compilation with MinGW broken

### ISSUE THREAD

**Issue by abbec** [oxalica/rust-overlay#59]
Hi,

c7ed82b2317b6b0d3d3a55ce4d12561f868858d0 broke our cross-compilation for Windows. It seems that with this change, `buildInputs` (i.e. `depsHostTarget`) end up in the linker for the `build` platform (i.e. Linux) which results in ` /nix/store/5ddb4j8z84p6sjphr0kh6cbq5jd12ncs-binutils-2.35.1/bin/ld: /nix/store/pl9raxwyb6jg662ljd9f1q3hrb2cni8l-pthreads-w32-x86_64-w64-mingw32-2.9.1/lib/libpthread.a: error adding symbols: file format not recognized`.

The commit before c7ed82b2317b6b0d3d3a55ce4d12561f868858d0 works as expected.

`NIX_LDFLAGS` and `NIX_LDFLAGS_FOR_BUILD` looks the same in both a working and non-working case though?

**Comment by abbec** [comment]
It looks like the same problem discussed at the end of #52, and it did work before c7ed82b2317b6b0d3d3a55ce4d12561f868858d0 so I think the issue is in here, or it exposed an issue in Nixpkgs.

**Comment by abbec** [comment]
Actually there is a small difference in `*_LDFLAGS`:

Working:
```
❯ echo $NIX_LDFLAGS
-L/nix/store/14s60q99gfkm52rfzfxry60cnm1f463j-mcfgthreads-x86_64-w64-mingw32-git/lib -L/nix/store/pl9raxwyb6jg662ljd9f1q3hrb2cni8l-pthreads-w32-x86_64-w64-mingw32-2.9.1/lib

❯ echo $NIX_LDFLAGS_FOR_BUILD
-L/nix/store/6bsh70027xrmjsqjxn5wpmwcl2xq8mg0-rust-default-1.53.0/lib -L/nix/store/2jh1myphkbxwwnw9zry684lybg3skgs4-file-5.39/lib
```

Not working:
```
❯ echo $NIX_LDFLAGS
-L/nix/store/14s60q99gfkm52rfzfxry60cnm1f463j-mcfgthreads-x86_64-w64-mingw32-git/lib -L/nix/store/14s60q99gfkm52rfzfxry60cnm1f463j-mcfgthreads-x86_64-w64-mingw32-git/lib -L/nix/store/pl9raxwyb6jg662ljd9f1q3hrb2cni8l-pthreads-w32-x86_64-w64-mingw32-2.9.1/lib -L/nix/store/pl9raxwyb6jg662ljd9f1q3hrb2cni8l-pthreads-w32-x86_64-w64-mingw32-2.9.1/lib

❯ echo $NIX_LDFLAGS_FOR_BUILD
-L/nix/store/q25xrjk7sq5pfqnr50xbmkrrkdab2nj1-rust-default-1.53.0/lib -L/nix/store/2jh1myphkbxwwnw9zry684lybg3skgs4-file-5.39/lib
```

So it is added twice in the case it does not work?

**Comment by abbec** [comment]
Note also that you will only be able to repro this error when you have a `build.rs`.

**Comment by abbec** [comment]
I have created an example+repro case in #60. Feel free to only use it to reproduce the issue or keep it as a permanent example/test :)

**Comment by abbec** [comment]
Commenting out propagatedBuildInputs on https://github.com/oxalica/rust-overlay/blob/885ef5bf9d2857dff8689292aedb511dfc952862/rust-overlay.nix#L208, and instead adding `depsBuildBuild = [ buildPackages.stdenv.cc ]` in my derivation fixes both this issue and #54 (!?).

**Comment by oxalica** [comment]
> Commenting out propagatedBuildInputs on
> 
> https://github.com/oxalica/rust-overlay/blob/885ef5bf9d2857dff8689292aedb511dfc952862/rust-overlay.nix#L208
> , and instead adding `depsBuildBuild = [ buildPackages.stdenv.cc ]` in my derivation fixes both this issue and #54 (!?).

I use `propagatedBuildInputs` at first time because I want to add `gcc` to both downstream `depsBuildBuild` (for build script linking) and `nativeBuildInputs` (for crate linking). You reminds me that the former should actually be `depsHostHostPropagated` on our side. But the latter one is surely `propagatedBuildInputs`.

Here the issue is that CC wrapper for build script thinks it's from `nativeBuildInputs` and add `NIX_LDFLAGS` instead of `NIX_LDFLAGS_FOR_BUILD`, thus trying to link wrong libraries. 
I'm working on this.

**Comment by abbec** [comment]
Thank you! Yeah, this seems like more of a nixpkgs bug?

**Comment by oxalica** [comment]
Found that I `stdenv.cc` is always brought from `buildPackages` so `pkgsHostTarget.stdenv.cc` actually equals `pkgsBuildHost.gcc`, thus I used to pull in wrong `cc`s.

Now it's fixed.
