### ISSUE TITLE
Example of exposing multiple rust toolchains from flake

### ISSUE THREAD

**Issue by brendanzab** [oxalica/rust-overlay#65]
Often as a crate author I'd like to be able to develop against multiple toolchains locally and run tests against them in CI builds. For example I usually check the following in CI:

- a pinned "minimum supported rust version"
- the latest stable
- the latest beta (to be a good citizen, staying aware of potential regressions in beta)
- the latest nightly (to keep on top of future updates)

I'm not exactly sure how to do this using the current Rust overlay. It would be really neat to see an example of this in the repository (I went looking but couldn't find one). Here's [an example from `actions-rs`](https://github.com/actions-rs/meta/blob/master/recipes/msrv.md) of something similar.

**Comment by oxalica** [comment]
As suggested by @dramforever, you can use define multiple development environments in `packages.*`.
Here's an example modified [from README](https://github.com/oxalica/rust-overlay#use-in-devshell-for-nix-develop).
```nix
{
  description = "A devShell example";

  inputs = {
    nixpkgs.url      = "github:nixos/nixpkgs/nixos-unstable";
    rust-overlay.url = "github:oxalica/rust-overlay";
    flake-utils.url  = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, rust-overlay, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        overlays = [ (import rust-overlay) ];
        pkgs = import nixpkgs {
          inherit system overlays;
        };
      in
      with pkgs;
      rec {
        # Use `nix develop .#stableShell` to enter each dev env.
        packages.stableShell = mkShell {
          packages = [ rust-bin.stable.latest.default ];
        };
        packages.nightlyShell = mkShell {
          packages = [ rust-bin.nightly."2021-12-03".default ];
        };
        packages.msrvShell = mkShell {
          packages = [ rust-bin.stable."1.43.0".default ];
        };

        # The default one for `nix develop` without argument.
        devShell = packages.stableShell;
      }
    );
}
```

For CI, just use `--command` to run script.
```
$ nix develop .#msrvShell --command rustc --version
rustc 1.43.0 (4fb7144ed 2020-04-20)
```

**Comment by oxalica** [comment]
Also worth mentioning that, you can do some Nix trick to directly include MSRV from `Cargo.toml`.
```nix
        packages.msrvShell = mkShell {
          packages = let
            msrv = (builtins.fromTOML (builtins.readFile ./Cargo.toml)).package.rust-version;
          in [ rust-bin.stable.${msrv}.default ];
        };
```

**Comment by brendanzab** [comment]
This is very helpful! Sorry it was a bit challenging to figure out how to put all the pieces together, so I appreciate the help!

**Comment by brendanzab** [comment]
Is there any reason why you use `packages.stableShell` as opposed to something like `devShells.stable`?

**Comment by oxalica** [comment]
> Is there any reason why you use `packages.stableShell` as opposed to something like `devShells.stable`?

Oh I just know `devShells` also exists. Yes, `devShells.<name>` would be better.

Usually the layout defined in flake outputs doesn't really matter and should all work if you specify its full path. It's just a convention for some default commands and is checked by `nix flake check`.
