### ISSUE TITLE
Question: Installing cargo plugins?

### ISSUE THREAD

**Issue by wkral** [oxalica/rust-overlay#67]
Is there a preferred way to install plugins for cargo? It seems to me like it should be part of the overlay as the version of cargo is coming from the overlay, but maybe there is another way.

I've seen some examples of people doing it with `shellHooks` but I seem to run into networking issues as I sort of would have expected. I can do it after I've entered into a nix-shell, but would really prefer if it was declarative and automated. Or if there is already a way, I haven't been able to find documentation for it.

**Comment by oxalica** [comment]
What's cargo plugins? If you mean custom cargo subcommands like `cargo-edit` or etc., they are just individual programs, totally independent from `cargo` itself. You can install them anywhere using any methods, from `nixpkgs` or compile-and-install by yourself. `cargo xxx` will automatically search `$CARGO_HOME/bin` or `~/.cargo/bin` and `$PATH` for any executable named `cargo-xxx` and run it.

**Comment by wkral** [comment]
Yes that's what I meant, thank you. I didn't understand that they would work that way, thought it had to be more tied into the installation of cargo based on how some other language packages work. Thanks for your help, probably should have been able to figure that one out on my own.
