### ISSUE TITLE
Latest available nightly is `nightly-2022-01-19` (CI failing for 5 days)

### ISSUE THREAD

**Issue by nerosnm** [oxalica/rust-overlay#71]
It looks like the last successful `sync-channels` CI run was from [6 days ago](https://github.com/oxalica/rust-overlay/actions/runs/1721346333) (and the `CI` job has been failing too). As a result, the latest available nightly version through this overlay is `2022-01-19`.

**Comment by oxalica** [comment]
Sorry I'm not available recently. I'd appreciate it if someone could make a PR to fix the update script..

**Comment by oxalica** [comment]
The update script is fixed in 264468bbc38786e3733926fd5c9e4744b63811b5. Manifests are up to date now.
