### ISSUE TITLE
Cargo error: `failed to resolve address for github.com`

### ISSUE THREAD

**Issue by Mr-Andersen** [oxalica/rust-overlay#72]
I have these [default.nix](https://gitlab.com/aka_dude/lobsters-best-bot/-/blob/nix-build/default.nix) and [build.sh](https://gitlab.com/aka_dude/lobsters-best-bot/-/blob/nix-build/build.sh). When I run `nix-build` I get:
```
> nix-build
these derivations will be built:
  /nix/store/xba0wbj0ki1fcwwjlskhiiq63r839dna-lobsters-best-bot.drv
building '/nix/store/xba0wbj0ki1fcwwjlskhiiq63r839dna-lobsters-best-bot.drv'...
    Updating crates.io index
warning: spurious network error (2 tries remaining): failed to resolve address for github.com: Name or service not known; class=Net (12)
warning: spurious network error (1 tries remaining): failed to resolve address for github.com: Name or service not known; class=Net (12)
error: failed to get `anyhow` as a dependency of package `lobsters-best-bot v0.1.0 (/nix/store/g5d7422cxp3v3xdy0hl44h0l3jwsavj2-lobsters-best-bot)`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  failed to resolve address for github.com: Name or service not known; class=Net (12)
builder for '/nix/store/xba0wbj0ki1fcwwjlskhiiq63r839dna-lobsters-best-bot.drv' failed with exit code 101
error: build of '/nix/store/xba0wbj0ki1fcwwjlskhiiq63r839dna-lobsters-best-bot.drv' failed
```
However, `nix-shell -p cargo --run 'cargo check'` runs fine.

I tried using rust-overlay via `nix-channel --add ...` before, if it's important.

**Comment by zhaofengli** [comment]
For reproducibility, the build sandbox normally cannot have network access (`nix-shell` is run outside of the sandbox). Rust packages in nixpkgs are typically built with [`buildRustPackage`](https://nixos.org/manual/nixpkgs/stable/#compiling-rust-applications-with-cargo), which first fetches all Cargo dependencies in a sandbox which allows network access with outputs pinned against a hash (known as a Fixed-Output Derivation), and then builds the application itself in a normal sandbox entirely offline. There are also alternative solutions like [naersk](https://github.com/nix-community/naersk) and [cargo2nix](https://github.com/cargo2nix/cargo2nix) which shift more of the work in the build process from Cargo onto Nix.

This isn't an issue with rust-overlay, and I recommend joining the [Nix Rust](https://matrix.to/#/#rust:nixos.org) Matrix channel if you need more help on that.

**Comment by Mr-Andersen** [comment]
@zhaofengli thank you! This makes perfect sense. Thank you for links.
