### ISSUE TITLE
`bpfel-unknown-none` / `bpfeb-unknown-none` support?

### ISSUE THREAD

**Issue by djahandarie** [oxalica/rust-overlay#79]
`bpfel-unknown-none` and `bpfeb-unknown-none` have been tier 3 targets since mid last year, as listed on https://doc.rust-lang.org/nightly/rustc/platform-support.html, and merged in https://github.com/rust-lang/rust/pull/79608.

I'm a bit confused why they aren't listed in https://github.com/oxalica/rust-overlay/blob/master/manifests/targets.nix.

Am I misunderstanding something about what rust-overlay can support?

**Comment by oxalica** [comment]
> `bpfel-unknown-none` and `bpfeb-unknown-none` have been tier 3 targets since mid last year,

This overlay (re)ships binary distributed rust toolchains from rustup server. If a target doesn't have `rustc`/`cargo` built, it's indeed not supported by us. We don't build anything. We just download and patch binaries from the rustup server.

> I'm a bit confused why they aren't listed in https://github.com/oxalica/rust-overlay/blob/master/manifests/targets.nix.

This file is generated from every nightly/stable/beta manifests TOML of rustup. It's a collection of all target having binaries available (from rustup server).
