### ISSUE TITLE
Doesn't work on Rust 1.60 and latter

### ISSUE THREAD

**Issue by Fuuzetsu** [oxalica/rust-overlay#81]
From Rust 1.60 cargo has introduced some new syntax for features

https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features

Seems rust-overlay isn't aware of these but it needs to be?

Initially I thought it was just the case of solving https://github.com/NixOS/nixpkgs/issues/90605#issuecomment-1092409045 but now I don't think so: presumably rust-overlay should be passing "already picked" features to the builder from nixpkgs but for now it passes through raw strings only.

**Comment by oxalica** [comment]
> From Rust 1.60 cargo has introduced some new syntax for features

We are just packaging `cargo`, `rustc` and etc for rust version managing to replace `rustup`. The behavior change of `cargo` itself doesn't do anything to us.

**Comment by Fuuzetsu** [comment]
Oops, sorry, I meant to create this on crate2nix repo. Sorry for the noise.
