### ISSUE TITLE
Is it possible to have multiple toolchains?

### ISSUE THREAD

**Issue by x3rAx** [oxalica/rust-overlay#82]
Hi, I'd like to use [`cargo-expand`](https://github.com/dtolnay/cargo-expand) (which requires a *nightly* toolchain to be installed, but not necessarily default) and use the *default* toolchain for building. 

The README says:

> Cargo expand relies on unstable compiler flags so it requires a nightly toolchain to be installed, though does not require nightly to be the default toolchain or the one with which cargo expand itself is executed. If the default toolchain is one other than nightly, running cargo expand will find and use nightly anyway.

When I use `rustup` and install a *nightly* toolchain, but keep the *stable* as the default, it works. However, when I enter my dev environment using `nix-shell shell.nix`, the `cargo expand` command can not find the *nightly* toolchain.

I've added `rust-overlay` to my `shell.nix` and in `nativeBuildInputs` I added

```
rust-bin.stable.latest.default
rust-bin.nightly.latest.default
```

However, `cargo check` can only find the stable toolchain.

Is there a way to make *nightly* available but keep *stable* as default toolchain?

**Comment by oxalica** [comment]
`cargo-expand` uses `+nightly` argument to use nightly toolchain. This argument is of `rustup`'s cargo wrapper and not supported by the real `cargo` binary provided by us.
https://github.com/dtolnay/cargo-expand/blob/1.0.17/src/main.rs#L107-L113

> I've added `rust-overlay` to my `shell.nix` and in `nativeBuildInputs` I added
> ```
> rust-bin.stable.latest.default
> rust-bin.nightly.latest.default
> ```
In `shell.nix`, `nativeBuildInputs` and friends describe how to construct `PATH`. Since the stable `cargo` and the nightly one have the same binary name, only the former is found first when typing `cargo` in your terminal.

> Is there a way to make nightly available but keep stable as default toolchain?

Typically nix "make something available" by exposing them in some env vars. But `PATH` only take effects on the first match.
Here you can use env vars `CARGO` and `RUSTC` to force programs using a specific toolchain, while keeping `PATH` the stable one, so your other operations will still work on the stable toolchain.

```nix
let
  nightly = rust-bin.selectLatestNightlyWith (t: t.default);
  # Wrap only `cargo-expand`.
  cargo-expand' = writeShellScriptBin "cargo-expand" ''
    export RUSTC="${nightly}/bin/rustc";
    export CARGO="${nightly}/bin/cargo";
    exec "${cargo-expand}/bin/cargo-expand" "$@"
  '';
in
mkShell {
  # Or `packages = [ .. ]` for short.
  nativeBuildInputs = [ rust-bin.stable.latest.default cargo-expand' ];
}
```

**Comment by x3rAx** [comment]
Thank you, this works great! :heart: 

I just had to prefix `writeShellScript` and `cargo-expand` (inside the script) with `pkgs.` (and there is also a single quote after the variable name of `cargo-expand` that needs to be removed ^^).

Also, thank you for the hint to use `packages` instead of `nativeBuildInputs` :smile_cat: 

I've got another question though:

Regarding the `RUST_SRC_PATH` variable export (see `shell.nix` below), is it correct to use `pkgs.rust.packages.stable...` or is there an equivalent for `rust-bin`?

---

So, just in case someone else finds this, my `shell.nix` now looks like this:

```nix
let
  rust-overlay = (import (builtins.fetchTarball
    "https://github.com/oxalica/rust-overlay/archive/4770c6c6cb518d2c5b660c5099816c3512d8bdad.tar.gz"));

  # Pinned nixpkgs, deterministic. Last updated: 2022-04-16T11:26:18Z [nixos-unstable].
  pkgs = import (fetchTarball(
    "https://github.com/NixOS/nixpkgs/archive/bc4b9eef3ce3d5a90d8693e8367c9cbfc9fc1e13.tar.gz")) {
      overlays = [ rust-overlay ];
    };

  rust-nightly = pkgs.rust-bin.selectLatestNightlyWith (toolchain: toolchain.default);
  # Wrap only `cargo-expand`.
  cargo-expand = pkgs.writeShellScriptBin "cargo-expand" ''
    export RUSTC="${rust-nightly}/bin/rustc";
    export CARGO="${rust-nightly}/bin/cargo";
    exec "${pkgs.cargo-expand}/bin/cargo-expand" "$@"
  '';
in pkgs.mkShell {
  name = "...";

  packages = with pkgs; [
    # ...
    rust-bin.stable.latest.default
    cargo-expand
    # ...
  ];

  # Certain Rust tools won't work without this
  # This can also be fixed by using oxalica/rust-overlay and specifying the rust-src extension
  # See https://discourse.nixos.org/t/rust-src-not-found-and-other-misadventures-of-developing-rust-on-nixos/11570/3?u=samuela. for more details.
  RUST_SRC_PATH = "${pkgs.rust.packages.stable.rustPlatform.rustLibSrc}";
}
```

**Comment by x3rAx** [comment]
> Regarding the RUST_SRC_PATH variable export (see shell.nix below), is it correct to use pkgs.rust.packages.stable... or is there an equivalent for rust-bin?

I just stumbled upon the answer to this question while closing browser tabs ^^'

Instead of the `RUST_SRC_PATH` export, one can override the rust package:

```nix
let
  # ...
in pkgs.mkShell {
  packages = with pkgs; [
    # ...
    (rust-bin.stable.latest.default.override {
      extensions = ["rust-src"];
    })
    # ...
  ];
}
```

**Comment by woojiq** [comment]
I just found a very trivial solution that I couldn't figure out for a year (no one mentioned this or I was just blind and young). Just create multiple `devShells` in the flake.
For exampe:
```nix
devShells.default = pkgs.mkShell {
  packages = with pkgs; [
    rust-bin.stable.latest.default
  ];
};
devShells.nightly = pkgs.mkShell {
  packages = with pkgs; [
    rust-bin.nightly."2024-02-01".default
  ];
};
```

And when you want to compile rust with nightly compiler you can run `nix develop .nightly`.
