### ISSUE TITLE
Can no longer compile with nixpkgs <21.11

### ISSUE THREAD

**Issue by evanjs** [oxalica/rust-overlay#83]
When attempting to build with nixpkgs master or 21.11, I am able to compile with the latest stable toolchain from rust-overlay master.

However, when using nixpkgs 20.09 or 21.05, my project fails to compile using the latest stable toolchain from rust-overlay master.

I believe this is a result of 4480130, the fix for #75.

Specifically, I believe this is related to the [changes](https://github.com/oxalica/rust-overlay/commit/44801306a2aa0e9aaa47588d615ce6df4acf18c6#diff-c56239498f0c3167f3944ccc77fa2658f9663761dc56c816775c8d1e6b00443eL2) to `mk-component-set`, based on the error message I was given:
```
error: anonymous function at /nix/store/dbph610vrj8r7yf73cxxjyas7vx01b8r-source/mk-component-set.nix:2:1 called without required argument 'bintools', at /nix/store/v9id935l4nh15l734anyyax2czla55ac-nixpkgs-src/lib/customisation.nix:69:16
```

Pinning rust-overlay to f7d4a3aabee883bfa4d8987a19446ca8f25df81f (the parent of 4480130, the suspect commit), allows my project to compile just fine.

If this is—technically speaking—not a bug, that's fine, but I figured I'd mention it here, as I try not to pin rust-overlay so that I am always using the latest Rust toolchain, regardless of the state of nixpkgs, and wanted to clarify whether there is an easy way I can continue to do that.

**Comment by oxalica** [comment]
Now nixpkgs <= 21.05 is explicitly marked as unsupported in https://github.com/oxalica/rust-overlay/commit/3bc2619665745f5e6f2efc3d0664edad4f62201b
