### ISSUE TITLE
how to set default stable?

### ISSUE THREAD

**Issue by PlumpMath** [oxalica/rust-overlay#85]
emacs ob-rust (org-mode org-babel)
https://github.com/micanzhang/ob-rust

error: no such subcommand: `+stable`

Thanks.

**Comment by oxalica** [comment]
The `+<something>` argument is a `rustup` flag. `rustup` would install fake `rustc` and `cargo` to handle special arguments like `+stable`. But `rust-overlay` are shipping `rustc`, `cargo` and etc binaries directly from upstream. The version is specified using nix syntax.
The related code is located in [rust-script](https://github.com/fornwall/rust-script/blob/adfb5beee2ac60982c07fe0138d3e89bb89b5f36/src/main.rs#L1163). Please don't use the argument `--toolchain-version` of `rust-script` to make it work.

**Comment by PlumpMath** [comment]
The option is not included anywhere (also "-c"), but I can't solve it. I don't know how to solve it. heh
