### ISSUE TITLE
how to install rust-bin.stable.latest.default with override & attribute?

### ISSUE THREAD

**Issue by PlumpMath** [oxalica/rust-overlay#86]
The reason for installing like this is because of rustpython --all-feature.
If you install rust with rust-bin(overlay) and then install cargo (in terminal command-line).
but that the build failed under nix management. 

So my questions are twofold.
Can rust-overlay replace the default rust?
And, is that override possible in a replaceable state like screenshot?

<img width="1665" alt="스크린샷 2022-04-27 오전 6 40 00" src="https://user-images.githubusercontent.com/1218365/165397097-902330a1-dbd7-4282-91ed-21b2d4ee2fe4.png">

error: attribute 'stable' missing

       at /nix/store/539dqak2dybhadcf56kvsvqhfhgmaiic-source/rust/default.nix:70:5:

           69|     # rust-bin
           70|     rust-bin.stable.latest.default
             |     ^
           71|

       … while evaluating the attribute 'value'

       at /nix/store/rzzik57xa7slfr3yx9knfqla9hw6731d-source/lib/types.nix:408:38:

          407|               elemType
          408|               [{ inherit (def) file; value = def'; }]
             |                                      ^
          409|             ).optionalValue

       … while evaluating 'dischargeProperties'

**Comment by oxalica** [comment]
You already selects `rust-bin.stable.latest.default.override { .. }` in the right-hand-side panel of your screenshot, which produces your customized toolchain derivation. And you import the result in the left-hand-side panel using `callPackages` to a name `rust-bin`, (assuming the right-hand-side file is just the `macos.nix`,), select another `.stable.latest.default` on the result. Of course it would fail. Just keep the line before the commit, and it would be fine.

Note that `.default` means selecting the ["default profile"](https://rust-lang.github.io/rustup/concepts/profiles.html#profiles) from the rustup server. A profile is a set of components, and the "default profile" contains `cargo`, `rustc`, `rust-std` and some other ones. You don't need to write `rustc`, `cargo` or `rust-std` explicitly. `extensions = ` is the way to adding more components to its output.

**Comment by PlumpMath** [comment]
Is there any way to automate the setup for rustup with nix?
I just installed stable with rustup and manually set the default profile, so even the rust-script/ob-rust problem seems to be solved.
.
someday..
Only overriding the global rustPlatform is resolved, so I want to install and develop all kinds of rust crates easily.

**Comment by PlumpMath** [comment]
https://rust-lang.github.io/rustup/overrides.html

Making the toolchain explicitly nix-managed will solve this.

**Comment by oxalica** [comment]
Generally, `rust-overlay` is expected to be used per-workspace, explicitly, using `nix-shell` or `nix shell`. So it would not pollute your global environment. Or if you want to install it globally (in `/run/current-system`), it would conflict with `rustup`, so only one of them could be installed at the same time.

Sorry but I'm not familiar with emacs or ob-rust. Hope it helps.

**Comment by PlumpMath** [comment]
Actually, I don't think that's the problem either. I don't know either. Whatever the problem, I'm just not using emacs org-babel rust for now. Simple, convenient, and great with just the overlay and crate2nix you made.
