### ISSUE TITLE
undefined symbol _dl_audit_symbind_alt in rust-analyzer

### ISSUE THREAD

**Issue by seriousbusinessuser** [oxalica/rust-overlay#90]
Hi,

I've encountered the error described in https://github.com/rust-lang/rust-analyzer/issues/12410 and not sure how to fix it. Is it because NixOS uses older `glibc` than required by `rust-analyzer`? My Rust setup:
```
      rust = rust-bin.selectLatestNightlyWith (toolchain: toolchain.default.override {
        extensions = [
          "cargo" "clippy" "rust-docs" "rust-std"
          "rustc" "rustfmt" "rust-analyzer-preview"
          "rust-src"
        ];
      });

```

**Comment by oxalica** [comment]
`rust-overlay` provides compilers, not libraries. The issue seems unrelated.
Or are you building `rust-analyzer` yourself with `rust-overlay`?

**Comment by oxalica** [comment]
Close as unrelated.

**Comment by mplanchard** [comment]
@seriousbusinessuser I made a comment on that other issue that might help you out: https://github.com/rust-lang/rust-analyzer/issues/12410#issuecomment-1220736341

**Comment by zhaofengli** [comment]
You have enabled the `rust-analyzer-preview` extension, and the `rust-analyzer` executable should be available inside the package. You should use that one instead of installing it yourself from another source.
