### ISSUE TITLE
Incompatible with nixpkgs-21.05: `-l: command not found`

### ISSUE THREAD

**Issue by bjornfor** [oxalica/rust-overlay#91]
[Yes, I know nixpkgs-21.05 is EOL, but for $dayjob I unfortunately need python-3.6, so I'm stuck with nixpkgs-21.05 for now. I just wanted to document this, and _hope_ it can be fixed.]

I ran `git bisect` and it points to 44801306a2aa0e9aaa47588d615ce6df4acf18c6 ("Fix WASI target by getting rid of CC") as the first bad commit.

With this repro.nix file:

```nix
let
  pkgs = import ~/nixpkgs-21.05 { overlays = [ (import ~/rust-overlay) ]; };
in
  pkgs.rust-bin.stable."1.56.0".default
```

builds fail like this:

```
$ nix-build ./repro.nix
...
checking for references to /build/ in /nix/store/nlcl8qn89v2zclsfay1h4ky1ia3wy21l-cargo-1.56.0-x86_64-unknown-linux-gnu...
automatically fixing dependencies for ELF files
/nix/store/sds4msgr38nfs2zg3fsrd54wv8sndlyx-auto-patchelf-hook/nix-support/setup-hook: line 220: -l: command not found
builder for '/nix/store/j27qj2lazzz8pgszfshf68nh9svkr1nm-cargo-1.56.0-x86_64-unknown-linux-gnu.drv' failed with exit code 127
cannot build derivation '/nix/store/3gqdqbs2d4d28r0z5rj9j46m7xxjw0d0-rust-default-1.56.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/3gqdqbs2d4d28r0z5rj9j46m7xxjw0d0-rust-default-1.56.0.drv' failed
```

It seems the shell/env variable `$READELF` is empty, causing `-l: command not found`.

**Comment by oxalica** [comment]
> [NixOS/nixpkgs@a7f5e83](https://github.com/NixOS/nixpkgs/commit/a7f5e8321e9db6f2cf2f3c6be7ce5cac28bff271)

With the PR merged, `rust-bin.stable."1.56.0".default` builds on `release-21.05` now.
